- .gitignore
- app.js
- bin/server.js
- env/app/Dockerfile
- env/app/run.sh
- env/up.sh
- index.js
- package.json
- runtests.sh
- tests/test.js
Create simple base app and Docker environment to run it in.
> Environment setup

- src/js/actions/user.js
- src/js/components/header/UserMenu.jsx
- src/js/flux.js
- src/js/server/datarouter.js
- src/js/stores/user.js
- src/scss/_base.scss
- src/scss/header/_base.scss
- src/scss/header/_medium.scss
This PR adds several features to the user menu:
* Shows actual username and active organization
* Supports organization switching
* Basic styling and layout
> User menu features

- src/js/components/form/Form.jsx
- src/js/components/form/InputBase.jsx
- src/js/components/form/SelectInput.jsx
- src/js/components/form/TextInput.jsx
This PR creates a simple form framework. The `Form` component is a wrapper for
any number of form fields, defined as concrete sub classes of the `InputBase`
base component.
The Form component renders the form fields in a concistent layout and manages
data entry and submission events. The `getValues()` and `getChangedValues()`
methods are convenient for working with the form output (e.g. sending only
the changed values in a PATCH request to the API).
> Form framework

- src/js/components/panes/PaneBase.jsx
- src/js/components/sections/SectionBase.jsx
- src/js/utils/PaneManager.js
- src/scss/_base.scss
- src/scss/_medium.scss
- src/scss/panes/_medium.scss
- src/scss/section/_medium.scss
- src/scss/style.scss
This PR implements the interactive (draggable) pane layout from an early
prototype.
> Pane layout

- src/js/components/header/Logo.jsx
- src/js/components/header/OrgPicker.jsx
- src/js/components/header/UserMenu.jsx
- src/scss/_base.scss
- src/scss/_variables.scss
- src/scss/header/_base.scss
- src/scss/header/_medium.scss
- src/scss/section/_medium.scss
- src/scss/style.scss
Add styling to header and user menu
> Header styling

- src/js/actions/location.js
- src/js/components/App.jsx
- src/js/components/forms/Form.jsx
- src/js/components/forms/LocationForm.jsx
- src/js/components/forms/PersonForm.jsx
- src/js/components/forms/inputs/TextArea.jsx
- src/js/components/misc/LocationMap.jsx
- src/js/components/misc/ViewSwitch.jsx
- src/js/components/panes/LocationPane.jsx
- src/js/components/sections/SectionBase.jsx
- src/js/components/sections/maps/LocationsPane.jsx
- src/js/components/sections/maps/MapsSection.jsx
- src/js/flux.js
- src/js/server/datarouter.js
- src/js/stores/location.js
- src/js/utils/PaneUtils.js
- src/scss/panes/_medium.scss
- src/scss/section/_medium.scss
Add the maps section with a locations sub-section, where locations are shown as
markers on a Google Map that can be clicked to view/edit location data.
> Maps section

- src/js/components/sections/people/PeopleListPane.jsx
- src/js/components/sections/people/PeopleSection.jsx
Remove dead code from people section and pane
> Remove dead code

- package.json
- src/js/components/sections/SectionBase.jsx
- src/scss/section/_base.scss
- src/scss/section/_medium.scss
Adds basic styling (still no icons) for the section nav menu.
> Section menu styling

- src/js/actions/action.js
- src/js/actions/campaign.js
- src/js/components/App.jsx
- src/js/components/header/search/CampaignMatch.jsx
- src/js/components/header/search/Search.jsx
- src/js/components/panes/CampaignPane.jsx
- src/js/components/sections/campaign/AllActionsPane.jsx
- src/js/components/sections/campaign/CampaignListPane.jsx
- src/js/components/sections/campaign/CampaignOverviewPane.jsx
- src/js/components/sections/campaign/CampaignPlannerPane.jsx
- src/js/components/sections/campaign/CampaignSection.jsx
- src/js/flux.js
- src/js/server/datarouter.js
- src/js/server/search.js
- src/js/stores/action.js
- src/js/stores/campaign.js
- src/js/utils/PaneUtils.js
- src/scss/panes/_medium.scss
This PR adds a skeleton of crude components for the campaign section and it's sub-sections. It also adds loading of campaign and action data and implements campaign search.
> Campaign section skeleton

- src/js/actions/search.js
- src/js/components/App.jsx
- src/js/components/KeyboardShortcuts.jsx
- src/js/components/header/search/Search.jsx
- src/js/components/sections/SectionBase.jsx
- src/js/stores/search.js
- src/scss/_base.scss
Adds support for global keyboard shortcuts and a keyboard shortcut reference overlay. The shortcuts implemented herein are:
* `gh`, `gp`, `gm` to navigate to home, people and maps sections respectively
* `//` to focus search field
* `?` to show shortcut reference
* `ESC` to close shortcut reference or cancel search
> Keyboard shortcuts

- gulpfile.js
- package.json
- src/js/actions/action.js
- src/js/actions/activity.js
- src/js/actions/participant.js
- src/js/components/App.jsx
- src/js/components/KeyboardShortcuts.jsx
- src/js/components/forms/ActionForm.jsx
- src/js/components/forms/inputs/RelSelectInput.jsx
- src/js/components/misc/actionlist/ActionList.jsx
- src/js/components/misc/actionlist/ActionListItem.jsx
- src/js/components/misc/actionlist/ParticipantItem.jsx
- src/js/components/misc/elements/Action.jsx
- src/js/components/misc/elements/Person.jsx
- src/js/components/panes/EditActionPane.jsx
- src/js/components/panes/MoveParticipantsPane.jsx
- src/js/components/sections/campaign/AllActionsPane.jsx
- src/js/flux.js
- src/js/server/datarouter.js
- src/js/stores/action.js
- src/js/stores/activity.js
- src/js/stores/participant.js
- src/js/stores/person.js
- src/js/utils/PaneUtils.js
- src/scss/actionlist/_base.scss
- src/scss/actionlist/_medium.scss
- src/scss/panes/_medium.scss
- src/scss/style.scss
This PR implements the actions list from an early prototype, with draggable participants. It also adds an EditActionPane and the necessary flux actions and store logic to make it work.
> Action list

- src/js/actions/activity.js
- src/js/components/forms/ActivityForm.jsx
- src/js/components/panes/AddActivityPane.jsx
- src/js/components/panes/EditActivityPane.jsx
- src/js/components/sections/campaign/AllActivitiesPane.jsx
- src/js/components/sections/campaign/CampaignSection.jsx
- src/js/server/datarouter.js
- src/js/stores/activity.js
- src/js/utils/PaneUtils.js
- src/scss/panes/_medium.scss
Add activity list to campaign section, and panes to add, edit and delete activities.
> Activity list and panes

- src/js/components/misc/Avatar.jsx
- src/js/components/misc/actionlist/ParticipantItem.jsx
- src/scss/actionlist/_medium.scss
Use avatars from new avatars.zetk.in in actions list.
> Person avatars

- src/js/components/misc/Avatar.jsx
- src/js/components/misc/actionlist/ActionList.jsx
- src/js/components/misc/actionlist/ActionListItem.jsx
- src/js/components/misc/actionlist/ContactSlot.jsx
- src/js/components/misc/actionlist/ParticipantItem.jsx
- src/js/components/misc/actionlist/ParticipantList.jsx
- src/js/stores/participant.js
- src/js/utils/StoreUtils.js
- src/js/utils/polyfills.js
- src/scss/actionlist/_base.scss
- src/scss/actionlist/_medium.scss
This contains a bunch of updates to the action list, such as:
* Nicer styling (accoarding to new visual concept with cards et c)
* Action contact slot with drag and drop
* Icon indicating number of additional participants where all can't be displayed at once
> Better action list

- src/js/components/misc/Avatar.jsx
- src/js/components/misc/peoplelist/PeopleList.jsx
- src/js/components/misc/peoplelist/PeopleListItem.jsx
- src/js/components/sections/people/PeopleListPane.jsx
- src/scss/peoplelist/_base.scss
- src/scss/peoplelist/_medium.scss
- src/scss/style.scss
This contains a proper PeopleList component instead of the old table which was
rendered in place in the PeopleListPane. Similar to the ActionList.
> Better person list

- src/js/components/panes/EditLocationPane.jsx
- src/js/components/panes/PersonPane.jsx
- src/js/components/sections/campaign/AllActionsPane.jsx
- src/js/components/sections/campaign/CampaignLocationsPane.jsx
Load what's necessary in some panes that were previously not properly handling
missing data.
> Pane preloading

- src/js/actions/participant.js
- src/js/components/misc/actionlist/ActionList.jsx
- src/js/components/misc/actionlist/ActionListItem.jsx
- src/js/components/panes/PersonPane.jsx
- src/js/stores/participant.js
- src/scss/panes/_medium.scss
This PR adds an avatar to the PersonPane.
It also makes that avatar draggable so that it's possible to search for a person, open it in a pane, and then drag and drop it onto an action to add it as a participant.
> Avatar in PersonPane

- src/js/components/KeyboardShortcuts.jsx
- src/js/stores/search.js
Fixes several issues (more or less) related to the search feature.
* Fix issue with closed connections
* Fix issue with search not commencing right away due to delayed connection
* Be more liberal about keyboard shortcuts
> Fix issues related to search

- src/js/components/panes/ActionDayPane.jsx
- src/js/components/panes/PaneBase.jsx
This PR makes improvements to the `ActionDayPane`.
* Adds prev/next buttons as discussed in #101
* Properly implements `ActionList` operations as discussed in #102
> Better ActionDayPane

- src/js/components/App.jsx
- src/js/components/KeyboardShortcuts.jsx
- src/js/components/sections/dialog/DialogSection.jsx
- src/js/components/sections/dialog/PlaceholderPane.jsx
- src/js/stores/dashboard.js
This pull request creates a placeholder "Dialog" section, where features like the callcenter will eventually be found.
Closes #58.
> Dialog section placeholder

- src/js/components/dashboard/Dashboard.jsx
- src/js/components/dashboard/Footer.jsx
- src/scss/dashboard/_base.scss
This PR creates a footer on the dashboard, with a short mission statement and links to the Zetkin Foundation and help pages.
Closes #126.
> Dashboard footer

- src/js/components/forms/ActionForm.jsx
Use UTC times and date in ActionForm.
Fixes #149.
> Fix ActionForm times

- src/js/components/sections/campaign/CampaignSection.jsx
Since we're not sure what exactly to display here, there is probably little use in having a sub-section like this. We might add it back if we come up with something we want to show here.
> Hide campaign overview

- src/js/actions/reminder.js
- src/js/components/misc/elements/Action.jsx
- src/js/components/panes/ActionDayPane.jsx
- src/js/components/panes/ActionReminderPane.jsx
- src/js/components/panes/index.js
- src/js/components/sections/campaign/AllActionsPane.jsx
- src/js/flux.js
- src/js/stores/participant.js
- src/scss/panes/_medium.scss
This PR adds logic and UI to send and inspect reminders sent to action participants.
The new `ActionReminderPane` contains a form to send reminders to any participants that have yet to receive one, as well as a list of reminders sent already.
Closes #164
> Action reminders

- src/js/actions/query.js
- src/js/client/main.js
- src/js/components/filters/CampaignFilter.jsx
- src/js/components/panes/EditQueryPane.jsx
- src/js/stores/query.js
This PR fixes some bugs related to the query feature, but also introduces mock logic for filters, to make sure that changing a filter changes the query result. This logic is completely nonsens, and will need to be removed once we have proper filter logic (implemented on the server).
> Make query feature ready for demoing

- src/js/components/forms/inputs/RelSelectInput.jsx
- src/js/components/header/search/Search.jsx
Fixes two bugs related to keyboard navigation.
* Search was stealing enter key presses from `RelSelectInput`
* Choosing the first option didn't work in `RelSelectInput`
> Keyboard bug fixes

- src/js/components/forms/ActionForm.jsx
- src/js/components/sections/people/PeopleListPane.jsx
- src/js/utils/StoreUtils.js
Fixes various issues discovered in the past day while planning demonstration.
* Properly handles UTC in `ActionForm`. Fixes #179
* Merges instead of replacing objects in `StoreUtils.updateOrAdd()`. Fixes #176
* Allows null value (no query) in `PeopleListPane` query selector. Fixes #177
> Various bugfixes

- src/js/components/forms/ActionForm.jsx
- src/js/components/panes/ActionDayPane.jsx
- src/js/components/panes/AddActionPane.jsx
- src/js/components/panes/AddActivityPane.jsx
- src/js/components/panes/AddCampaignPane.jsx
- src/js/components/panes/AddPersonPane.jsx
- src/js/components/panes/EditActionPane.jsx
- src/js/components/panes/EditActivityPane.jsx
- src/js/components/panes/EditCampaignPane.jsx
- src/js/components/panes/EditLocationPane.jsx
- src/js/components/panes/PersonPane.jsx
This PR fixes two things. 
* Add logic to close form panes when the user submits them. Closes #180
* Make campaign, activity and location edit panes accessible through the ActionForm.
> Improve opening/closing panes

- src/js/components/forms/inputs/RelSelectInput.jsx
* Fixes issue which was causing pane to scroll when scrolling `RelSelectInput`.
* Resets scroll when blurring or changing value
* Allows blurring using ESC key
> Tweak RelSelectInput scrolling

- src/js/components/misc/peoplelist/PeopleList.jsx
- src/js/components/misc/peoplelist/PeopleListHeader.jsx
- src/scss/peoplelist/_base.scss
Creates a new `PeopleListHeader` component which is not actually specific to `PeopleList`
(other than some CSS class names) and will be easy to reuse in a future general-purpose
list component as discussed in #44.
Closes #175
> Implement sorting in PeopleList

- src/js/components/panes/MoveParticipantsPane.jsx
- src/js/components/panes/QueryPane.jsx
- src/scss/panes/_medium.scss
- src/scss/peoplelist/_medium.scss
This PR contains fixes to two pane related bugs.
* Width of `MoveParticipantsPane` is no longer dependent on content. Fixes #192
* `QueryPane` can now reliably be rendered on the server. Fixes #194
> Pane bug fixes

- src/js/components/misc/actioncal/ActionDay.jsx
- src/scss/actioncal/_medium.scss
Style minical to indicate day and month change.
> Mini-calendar styling

- src/scss/filters/_base.scss
- src/scss/inputs/_base.scss
Adds icons in two places that had been forgotten and left with placeholders.
* The checkmark that marks the selected option in a `RelSelectInput`
* The close/remove button in query filters
> Missing icons

- src/js/components/misc/list/ListHeader.jsx
- src/js/components/misc/loclist/LocationList.jsx
- src/js/components/misc/loclist/LocationListItem.jsx
- src/js/components/misc/peoplelist/PeopleList.jsx
- src/js/components/sections/maps/LocationsPane.jsx
- src/scss/loclist/_base.scss
- src/scss/panes/_medium.scss
- src/scss/peoplelist/_base.scss
- src/scss/peoplelist/_medium.scss
- src/scss/style.scss
This PR adds a very simple location list. It also refactors the `PeopleListHeader` into a
general-purpose `ListHeader`, as another step towards #44.
Closes #178
> Location list

- src/scss/_mixins.scss
- src/scss/forms/_base.scss
Will need even more work eventually, but is fine for now and enough to postpone the rest of #54 until the next milestone.
> Improve styling of forms.

- README.md
(Exactly the same as the PR to accounts.)
> Add npm and gulp install steps to README.

- src/js/server/authrouter.js
- src/js/stores/user.js
Use the new variable ZETKIN_DOMAIN to configure which environment the app is
running in.
> Use ZETKIN_DOMAIN

- src/client/main.js
- src/components/App.jsx
- src/components/FluxComponent.jsx
- src/components/forms/ActionForm.scss
- src/components/forms/Form.jsx
- src/components/forms/Form.scss
- src/components/forms/inputs/DateInput.jsx
- src/components/forms/inputs/DateInput.scss
- src/components/forms/inputs/RelSelectInput.jsx
- src/components/forms/inputs/RelSelectInput.scss
- src/components/forms/inputs/SelectInput.scss
- src/components/misc/CampaignSelect.scss
- src/components/misc/ViewSwitch.jsx
- src/components/misc/ViewSwitch.scss
- src/components/panes/PaneBase.scss
- src/scss/_global.scss
- src/scss/_mixins.scss
- src/scss/_variables.scss
- src/server/app.js
This PR adds styling for the Form component, higher-order components and input fields. (Now properly branching off latest master as opposed to #238).
> Form styling

- src/components/filters/CallHistoryFilter.jsx
- src/components/filters/CallHistoryFilter.scss
- src/components/filters/FilterList.jsx
- src/components/filters/index.js
This PR creates filter UI for filters related to phone banking.
> Call filters

- src/components/forms/CallAssignmentForm.jsx
- src/components/misc/callerlist/CallerList.scss
- src/components/misc/callerlist/CallerListItem.jsx
- src/components/misc/callerlist/CallerListItem.scss
- src/components/misc/list/ListHeader.scss
- src/components/misc/peoplelist/PeopleList.scss
- src/components/misc/peoplelist/PeopleListItem.jsx
- src/components/misc/peoplelist/PeopleListItem.scss
- src/components/panes/CallAssignmentPane.jsx
- src/components/panes/CallAssignmentPane.scss
- src/components/panes/PaneBase.scss
- src/scss/_mixins.scss
This PR adds styling to the Call assignment pane and corresponding components.
> Call assignment styling

- src/components/filters/CampaignFilter.scss
- src/components/filters/FilterBase.jsx
- src/components/filters/FilterBase.scss
- src/components/filters/FilterList.scss
- src/components/filters/FilterOpSwitch.jsx
- src/components/filters/FilterOpSwitch.scss
- src/components/panes/PaneBase.scss
- src/components/panes/QueryPane.scss
- src/scss/_variables.scss
This PR gives styling enhancement to the Query pane.
Also, some color variables are introduced.
> Query panes styling

- src/components/misc/LoadingIndicator.jsx
- src/components/misc/LoadingIndicator.scss
- src/components/panes/CallAssignmentPane.jsx
- src/components/panes/CallAssignmentPane.scss
- src/scss/_mixins.scss
This PR adds styling to Call assignment stats of target and goals.
> Call assignment stats styling

- src/components/filters/FilterBase.scss
- src/components/filters/FilterList.jsx
- src/components/filters/FilterList.scss
- src/components/filters/FilterOpSwitch.scss
- src/components/misc/ViewSwitch.scss
- src/components/misc/tagcloud/TagCloud.scss
- src/components/misc/tagcloud/TagCloudItem.scss
- src/components/panes/EditCallerPane.jsx
- src/components/panes/PaneBase.scss
- src/components/panes/SelectPersonTagsPane.jsx
- src/components/panes/SelectPersonTagsPane.scss
- src/scss/_global.scss
- src/scss/_mixins.scss
This PR does various updates to the tag cloud and related panes and components.
> Tagcloud styling

- src/components/misc/actioncal/ActionCalendar.scss
- src/components/misc/actioncal/ActionDay.scss
- src/components/misc/actioncal/ActionItem.scss
- src/components/misc/actioncal/ActionMiniCalendar.scss
- src/components/panes/PaneBase.scss
- src/scss/_mixins.scss
This PR tweak the styling of the ActionCalendar and related components. Also, a refactor was made, making the styling component specific.
> ActionCalendar styling

- src/components/KeyboardShortcuts.jsx
- src/components/misc/campaignplayer/CampaignPlayer.scss
- src/components/misc/campaignplayer/CampaignPlayerTransport.scss
- src/components/misc/campaignplayer/Scrubber.jsx
- src/components/misc/campaignplayer/Scrubber.scss
- src/components/sections/campaign/CampaignPlaybackPane.scss
This PR adds some styling to the CampaignPlaybackPane and its components.
> Playback styling

- src/actions/index.js
- src/actions/invite.js
- src/components/misc/InviteBox.jsx
- src/components/misc/InviteBox.scss
- src/components/sections/index.js
- src/components/sections/people/InvitePane.jsx
- src/store/index.js
- src/store/invites.js
This PR adds interface to display previous invites and send new invites.
Closes #51.
> Invite interface

- src/components/lists/ActionList.scss
- src/components/lists/List.scss
- src/components/lists/PersonList.jsx
- src/components/misc/actioncal/ActionCalendar.jsx
- src/components/misc/actioncal/ActionDay.jsx
- src/components/misc/actioncal/ActionItem.jsx
- src/components/misc/actioncal/ActionMiniCalendar.jsx
- src/components/panes/ActionDayPane.jsx
- src/components/panes/CallAssignmentPane.jsx
- src/components/panes/QueryPane.jsx
- src/components/panes/SelectPeoplePane.jsx
- src/components/sections/campaign/ActionDistributionPane.jsx
- src/components/sections/campaign/AllActionsPane.jsx
- src/components/sections/campaign/CampaignPlaybackPane.jsx
- src/server/datarouter.js
- src/server/main.js
- src/server/widgets.js
- src/store/actions.js
UI bug fixes in preparation of tomorrow's shooting of the crowdfunding video.
> Bugfixes for crowdfunding video

- locale/lists/callAssignmentList/sv.yaml
- src/actions/search.js
- src/components/App.jsx
- src/components/filters/FilterList.jsx
- src/components/forms/Form.jsx
- src/components/forms/PersonForm.jsx
- src/components/forms/inputs/SelectInput.jsx
- src/components/header/search/Search.jsx
- src/components/lists/CallAssignmentList.jsx
- src/components/lists/CallAssignmentsList.jsx
- src/components/lists/items/CallAssignmentListItem.jsx
- src/components/lists/items/CallAssignmentListItem.scss
- src/components/panes/EditLocationWithMapPane.jsx
- src/components/sections/dialog/AllCallAssignmentsPane.jsx
- src/store/search.js
This PR contains a bunch of unsorted bug fixes.
> Various bug fixes

- src/actions/user.js
- src/server/app.js
- src/server/datarouter.js
- src/store/org.js
Refactor activist page redirect to sort out some bugs.
> Activist page

- locale/lists/sv.yaml
- src/actions/person.js
- src/components/lists/List.jsx
- src/components/lists/List.scss
- src/components/lists/PersonList.jsx
- src/components/misc/LoadingIndicator.scss
- src/components/sections/people/PeopleListPane.jsx
- src/store/people.js
- src/utils/store.js
This PR adds support for pagination to the List component, and implements it for the `PersonList`.
> Pagination

- locale/panes/import/sv.yaml
- src/components/misc/importer/ImporterColumnHead.jsx
- src/components/misc/importer/ImporterColumnHead.scss
- src/components/misc/importer/ImporterTable.jsx
- src/components/misc/importer/ImporterTable.scss
- src/components/misc/importer/ImporterTableRow.jsx
- src/components/misc/importer/ImporterTableRow.scss
- src/components/misc/importer/ImporterTableSet.jsx
- src/components/misc/importer/ImporterTableSet.scss
- src/components/misc/importer/settings/PersonTagColumnSettings.jsx
- src/components/panes/ImporterColumnPane.scss
- src/components/sections/people/ImportPane.jsx
- src/components/sections/people/ImportPane.scss
This PR gives the import section some much needed styling.
> Import styling

- locale/bulkOps/sv.yaml
- locale/panes/bulkOp/sv.yaml
- package.json
- src/actions/bulk.js
- src/components/misc/actioncal/ActionMiniCalendar.jsx
- src/components/sections/people/PeopleListPane.jsx
- src/server/api/bulk.js
This PR adds a bulk operation to export people from the person list to Excel.
> Person export

- locale/dashboard/sv.yaml
- src/components/dashboard/Dashboard.jsx
- src/components/dashboard/Dashboard.scss
- src/components/dashboard/Footer.jsx
- src/components/dashboard/Shortcut.jsx
- src/components/dashboard/Shortcut.scss
- src/store/dashboard.js
This PR adjusts the dashboard for launch, as explained in #333.
Closes #322
Closes #333
> Dashboard for launch

- src/components/App.jsx
- src/components/lists/ActionList.scss
- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ActionListItem.scss
- src/components/lists/items/elements/ContactSlot.scss
- src/components/lists/items/elements/ParticipantItem.scss
- src/components/lists/items/elements/ParticipantList.scss
- src/scss/_global.scss
This PR revamp the ActionList to follow the design proposal in #181.
Also includes adding the branded fonts as global.
Fixes #339
> ActionList styling

- src/components/misc/officiallist/OfficialList.scss
- src/components/misc/officiallist/OfficialListItem.jsx
- src/components/misc/officiallist/OfficialListItem.scss
> OfficialList styling

- locale/lists/callAssignmentList/sv.yaml
- src/components/lists/ActionList.scss
- src/components/lists/CallAssignmentList.jsx
- src/components/lists/CallAssignmentList.scss
- src/components/lists/List.scss
- src/components/lists/PersonList.scss
- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ActionListItem.scss
- src/components/lists/items/CallAssignmentListItem.jsx
- src/components/lists/items/CallAssignmentListItem.scss
- src/components/lists/items/ListItem.scss
- src/components/lists/items/PersonListItem.scss
- src/components/misc/ProgressBar.jsx
- src/components/misc/ProgressBar.scss
- src/components/panes/CallAssignmentPane.jsx
- src/components/panes/CallAssignmentPane.scss
This PR gives some styling according to proposals in #334 
Solves #334
> Call assignment list styling

- locale/header/sv.yaml
- locale/sections/sv.yaml
- src/components/App.jsx
- src/components/KeyboardShortcuts.jsx
- src/components/KeyboardShortcuts.scss
- src/components/fullpages/ActivistPage.jsx
- src/components/header/OrgUserMenu.jsx
- src/components/header/search/ScopeSelect.jsx
- src/components/header/search/ScopeSelect.scss
- src/components/misc/GoogleAnalytics.jsx
- src/components/panes/ActionReminderPane.jsx
- src/components/panes/AddActionPane.jsx
- src/components/panes/AddActivityPane.jsx
- src/components/panes/AddCampaignPane.jsx
- src/components/panes/AddPersonPane.jsx
- src/components/panes/EditActionPane.jsx
- src/components/panes/EditActivityPane.jsx
- src/components/panes/EditCallAssignmentPane.jsx
- src/components/panes/EditCampaignPane.jsx
- src/components/panes/EditLocationPane.jsx
- src/components/panes/EditPersonPane.jsx
- src/components/panes/EditQueryPane.jsx
- src/components/sections/Section.jsx
- src/components/sections/Section.scss
This PR contains fixes to various minor prioritized issues.
> Minor fixes

- locale/lists/callList/sv.yaml
- locale/panes/call/sv.yaml
- src/actions/call.js
- src/actions/index.js
- src/components/lists/CallList.jsx
- src/components/lists/CallList.scss
- src/components/lists/items/CallListItem.jsx
- src/components/lists/items/CallListItem.scss
- src/components/panes/CallPane.jsx
- src/components/panes/CallPane.scss
- src/components/sections/dialog/CallLogPane.jsx
- src/scss/_global.scss
- src/scss/_variables.scss
- src/store/calls.js
> CallList & CallPane styling

- src/components/misc/callAssignmentTemplates/AssignmentTemplate.jsx
- src/components/misc/callAssignmentTemplates/AssignmentTemplate.scss
- src/components/panes/AddCallAssignmentPane.scss
> Style AddCallAsignmentPane

- locale/misc/sv.yaml
- locale/panes/peopleList/sv.yaml
- locale/panes/sv.yaml
- src/components/forms/inputs/DateInput.scss
- src/components/forms/inputs/RelSelectInput.jsx
- src/components/forms/inputs/RelSelectInput.scss
- src/components/misc/CampaignSelect.jsx
- src/components/misc/CampaignSelect.scss
- src/components/misc/ViewSwitch.scss
- src/components/sections/RootPaneBase.jsx
- src/components/sections/RootPaneBase.scss
- src/components/sections/campaign/CampaignSectionPaneBase.jsx
- src/components/sections/people/InvitePane.scss
- src/components/sections/people/PeopleListPane.jsx
- src/components/sections/people/PeopleListPane.scss
- src/scss/_mixins.scss
> Filter drawer styling

- .babelrc
- gulpfile.js
- package.json
- webpack.config.js
This PR duplicates the recent fix to the production build system from zetkin/www.zetk.in#70.
> Upgrade to Webpack 2 and Babel 6

- package.json
- src/actions/search.js
- src/components/filters/CallHistoryFilter.jsx
- src/components/filters/CampaignFilter.jsx
- src/components/forms/ActionForm.jsx
- src/components/lists/items/CallListItem.jsx
- src/components/misc/actioncal/ActionItem.jsx
- src/components/misc/campaignplayer/CampaignPlayerTransport.jsx
- src/components/misc/campaignplayer/Transport.jsx
- src/components/misc/elements/Action.jsx
- src/components/panes/ActionPane.jsx
- src/components/panes/ActionReminderPane.jsx
- src/components/panes/AddCallAssignmentPane.jsx
- src/components/panes/CallPane.jsx
- src/server/search.js
- src/utils/polyfills.js
This PR includes improvements to date search:
* Optimized searching for actions using API filtering, closes #446
* Swedish locale supported in date searches, closes #311
> Enhanced date search

- src/components/lists/items/ListItem.jsx
- src/components/lists/items/ListItem.scss
> ListItem selection styling

- locale/lists/surveySubmissionList/sv.yaml
- locale/panes/surveySubmission/sv.yaml
- src/components/lists/SurveySubmissionList.jsx
- src/components/lists/SurveySubmissionList.scss
- src/components/lists/items/SurveySubmissionListItem.jsx
- src/components/lists/items/SurveySubmissionListItem.scss
- src/components/panes/SurveySubmissionPane.jsx
- src/components/panes/SurveySubmissionPane.scss
- src/scss/_mixins.scss
> Survey submission styling

- locale/panes/actionReminder/sv.yaml
- src/components/panes/ActionPane.jsx
- src/components/panes/ActionReminderPane.jsx
- src/components/panes/ActionReminderPane.scss
- src/store/participants.js
This PR fixes various minor issues related to action reminders. See commit messages for details.
> Misc reminder issues

- locale/lists/surveyList/sv.yaml
- locale/panes/survey/sv.yaml
- src/components/lists/SurveyList.jsx
- src/components/lists/SurveyList.scss
- src/components/lists/items/SurveyListItem.jsx
- src/components/lists/items/SurveyListItem.scss
- src/components/misc/surveyOutline/SurveyOutline.jsx
- src/components/misc/surveyOutline/SurveyOutline.scss
- src/components/misc/surveyOutline/SurveyOutlineElement.jsx
- src/components/misc/surveyOutline/SurveyOutlineElement.scss
- src/components/misc/surveyOutline/SurveyQuestionOption.jsx
- src/components/misc/surveyOutline/SurveyQuestionOption.scss
- src/components/misc/surveyOutline/SurveyQuestionOutline.scss
- src/components/panes/SurveyPane.jsx
- src/components/panes/SurveyPane.scss
- src/scss/_mixins.scss
This PR covers styling of the Survey list and builder.
Closes #486 
Closes #491
> Survey styling

- locale/panes/import/en.yaml
- locale/panes/import/sv.yaml
- package.json
- src/actions/importer.js
- src/components/misc/importer/ImporterColumnHead.scss
- src/components/misc/importer/ImporterTable.jsx
- src/components/misc/importer/ImporterTable.scss
- src/components/misc/importer/ImporterTableBody.jsx
- src/components/misc/importer/ImporterTableBody.scss
- src/components/misc/importer/ImporterTableHead.jsx
- src/components/misc/importer/ImporterTableRow.scss
- src/components/misc/importer/ImporterTableSet.jsx
- src/components/misc/importer/ImporterTableSet.scss
- src/components/misc/importer/settings/PersonTagColumnSettings.jsx
- src/components/panes/ImportPane.scss
- src/components/sections/people/ImportPane.scss
- src/scss/_mixins.scss
- src/utils/store.js
This PR improves the importer interface as described in #517.
> Importer improvements

- src/components/filters/CampaignFilter.jsx
- src/components/forms/inputs/RelSelectInput.jsx
- src/components/forms/inputs/RelSelectInput.scss
- src/components/lists/ActionList.jsx
- src/components/lists/List.jsx
- src/components/lists/items/ActionListItem.scss
- src/components/lists/items/elements/ParticipantList.jsx
- src/components/misc/LocationMap.jsx
- src/components/misc/importer/ImporterTableSet.scss
- src/components/panes/ActionPane.jsx
- src/components/panes/PlaceLocationPane.jsx
- src/components/sections/people/PeopleListPane.jsx
- src/utils/location.js
This PR introduces fixes to several bugs and usability issues.
> Misc fixes

- locale/filters/en.yaml
- locale/filters/surveyOption/en.yaml
- locale/filters/surveyOption/sv.yaml
- locale/filters/surveyResponse/en.yaml
- locale/filters/surveyResponse/sv.yaml
- locale/filters/surveySubmission/en.yaml
- locale/filters/surveySubmission/sv.yaml
- locale/filters/sv.yaml
- src/components/filters/FilterList.jsx
- src/components/filters/SurveyOptionFilter.jsx
- src/components/filters/SurveyResponseFilter.jsx
- src/components/filters/SurveyResponseFilter.scss
- src/components/filters/SurveySubmissionFilter.jsx
- src/components/filters/index.js
This PR adds UI "Smart search" query filters related surveys.
> Survey query filters

- src/components/App.scss
- src/components/panes/PaneBase.jsx
- src/components/panes/PaneBase.scss
- src/components/sections/RootPaneBase.scss
Se commits for details.
Also fixes #560
> Pane styling fixes

- src/components/misc/Button.jsx
- src/components/panes/ActionReminderPane.jsx
- src/scss/_mixins.scss
- src/store/actions.js
- src/store/participants.js
This PR checks if reminders has been sent and disables the button until they left pending state. Thus fixes #551.
At the same time, we also updates the Button component to handle isPending by adding a class name for styling and disabling clicks if true.
The pending class is used in the button mixin to add a css animation with linear-gradients.
> Pending reminders

- locale/panes/action/en.yaml
- locale/panes/action/sv.yaml
- src/components/misc/ActionBox.jsx
- src/components/misc/ActionBox.scss
- src/components/misc/personcollection/PersonCollection.scss
- src/components/misc/personcollection/items/PCActionParticipantItem.jsx
- src/components/misc/personcollection/items/PCActionParticipantItem.scss
- src/components/misc/personcollection/items/PCActionResponseItem.jsx
- src/components/panes/ActionPane.jsx
- src/components/panes/ActionPane.scss
> Action Pane styling

- package.json
- src/actions/search.js
- src/server/search.js
- src/utils/searchMatches.js
This PR includes several fixes and improvements to the real-time search in Organize. Searching is now fuzzy, limited to 20 matches, and the groundwork has been laid for displaying the matching key in the search results in a future interface update.
> Search improvements

- locale/panes/action/en.yaml
- locale/panes/action/sv.yaml
- src/components/misc/ActionBox.jsx
- src/components/panes/ActionPane.jsx
- webpack.config.js
This PR fixes some issues with the reminder section/action box in `ActionPane`. See commits for details.
> Fix reminder quirks

- locale/forms/person/en.yaml
- locale/forms/person/sv.yaml
- locale/panes/addQuery/en.yaml
- locale/panes/addQuery/sv.yaml
- package.json
- src/actions/query.js
- src/components/forms/PersonForm.jsx
- src/components/misc/actioncal/ActionCalendar.jsx
- src/components/misc/importer/ImporterTableRow.scss
- src/components/panes/AddQueryPane.jsx
- src/components/panes/QueryPane.jsx
- src/components/panes/SurveySubmissionPane.jsx
- src/components/panes/index.js
- src/components/sections/people/PeopleListPane.jsx
- src/store/queries.js
- src/store/view.js
- src/utils/import.js
- src/utils/polyfills.js
This PR contains fixes to various minor bugs that have been reported recently.
> Misc bugfixes

- package.json
- src/server/app.js
This PR implements reporting of errors to Sentry, along with version numbers.
> Error reporting

- src/components/forms/SurveyQuestionForm.jsx
- src/components/misc/Avatar.jsx
- src/components/misc/importer/ImporterTable.jsx
- src/components/panes/CallPane.jsx
- src/components/panes/CallPane.scss
- src/utils/PaneManager.js
This PR makes a number of small improvements and fixes some minor bugs. See commit log for details.
> Misc improvements

- locale/panes/surveySubmissions/en.yaml
- locale/panes/surveySubmissions/sv.yaml
- src/actions/surveySubmission.js
- src/components/sections/survey/SurveySubmissionsPane.jsx
- src/store/surveySubmissions.js
This PR adds a feature to filter by survey in the `SurveySubmissionsPane` which lists all survey submissions.
> Survey submission filters

- src/server/search.js
- src/utils/searchMatches.js
This PR optimizes the simple search function by caching data, batching (and "green-threading") the matcher logic, and aborting running search process when the query changes.
> Optimized search

- locale/panes/route/en.yaml
- locale/panes/route/sv.yaml
- src/components/panes/RoutePane.jsx
- src/components/panes/RoutePane.scss
- src/components/panes/index.js
- src/components/sections/canvass/AllRoutesPane.jsx
- src/components/sections/canvass/AllRoutesPane.scss
- src/components/sections/canvass/elements/RouteList.jsx
- src/components/sections/canvass/elements/RoutePanel.jsx
This PR adds `RoutePane` and related features, and will be merged into feature/canvass when ready.
> Canvass RoutePane

- src/components/misc/InfoList.jsx
- src/components/misc/InfoList.scss
- src/components/panes/AddressPane.jsx
- src/components/panes/AddressPane.scss
- src/components/panes/index.js
- src/components/sections/canvass/AllRoutesPane.jsx
- src/components/sections/canvass/AllRoutesPane.scss
- src/utils/location.js
- src/utils/store.js
This PR adds an `AddressPane` to the feature/canvass branch.
> Canvass AddressPane

- locale/misc/en.yaml
- locale/misc/sv.yaml
- locale/panes/addCallAssignment/en.yaml
- locale/panes/addCallAssignment/sv.yaml
- src/actions/survey.js
- src/components/filters/SurveyOptionFilter.jsx
- src/components/forms/SurveyQuestionForm.jsx
- src/components/misc/callAssignmentTemplates/SurveyTemplate.jsx
- src/components/panes/AddCallAssignmentPane.jsx
- src/components/panes/AddSurveyPane.jsx
- src/components/panes/AddSurveyQuestionPane.jsx
- src/store/view.js
This PR fixes two issues related to surveys. See commit log for details.
> Survey-related bugfixes

- bin/build_dev.cmd
- bin/run_dev.cmd
The scripts I needed to get this running on my Windows machine.
> Add windows docker scripts

- src/components/forms/inputs/RelSelectInput.jsx
Fix the stepping bug described in issue #600
> Fix scroll bug described in issue #600

- src/components/misc/InfoList.jsx
- src/components/panes/AddressPane.jsx
- src/components/panes/PersonPane.jsx
- src/components/panes/PersonPane.scss
- src/components/panes/RouteFromAddressesPane.jsx
- src/components/panes/RoutePane.jsx
- src/components/panes/RoutePane.scss
- src/components/sections/canvass/elements/AddressSelectionPanel.jsx
Restructure how the `InfoList` Component work and use it in more places
> Refactor and use InfoList in more places

- src/components/misc/InfoList.jsx
- src/components/misc/Link.jsx
- src/components/panes/ActionPane.jsx
- src/components/panes/ActionPane.scss
- src/components/panes/CallAssignmentPane.jsx
- src/components/panes/CallAssignmentPane.scss
- src/components/panes/PersonPane.scss
- src/components/panes/SurveyPane.jsx
- src/components/panes/SurveyPane.scss
> Use InfoList on more places

- locale/panes/address/en.yaml
- locale/panes/address/sv.yaml
- locale/panes/routeFromSelection/da.yaml
- locale/panes/routeFromSelection/en.yaml
- locale/panes/routeFromSelection/sv.yaml
- src/actions/route.js
- src/components/panes/AddressPane.jsx
- src/components/panes/AddressPane.scss
- src/components/panes/RouteFromAddressesPane.jsx
- src/components/sections/canvass/AllRoutesPane.jsx
- src/components/sections/canvass/elements/AddressMap.jsx
- src/components/sections/canvass/elements/RoutePanel.jsx
- src/components/sections/canvass/elements/RoutePanel.scss
- src/server/app.js
- src/store/addresses.js
This PR contains a number of minor improvements to the route planning process, including performance optimization, workflow optimization and bug fixes.
> Route planning optimizations

- locale/panes/assignedRoute/en.yaml
- locale/prints/assignedRoute/en.yaml
- package.json
- src/actions/index.js
- src/actions/print.js
- src/client/main.js
- src/components/panes/AssignedRoutePane.jsx
- src/components/panes/AssignedRoutePane.scss
- src/components/prints/AssignedRoutePrint.jsx
- src/components/prints/AssignedRoutePrint.scss
- src/server/app.js
- src/server/prints.js
- src/store/index.js
- src/store/prints.js
Add printouts to the `AssignedRoutePane` introduced by PR #663.
> Visit log: printable assigned routes

- locale/panes/allActions/da.yaml
- locale/panes/allActions/en.yaml
- locale/panes/allActions/sv.yaml
- src/actions/action.js
- src/components/forms/inputs/SelectInput.jsx
- src/components/sections/campaign/ActionDistributionPane.jsx
- src/components/sections/campaign/AllActionsPane.jsx
- src/components/sections/campaign/CampaignPlaybackPane.jsx
- src/components/sections/campaign/CampaignSectionPaneBase.jsx
- src/server/datarouter.js
- src/store/actions.js
This PR improves the filters in the campaign/action sub-sections, and adds a filter by activity.
> Action filters

- locale/filters/da.yaml
- locale/filters/en.yaml
- locale/filters/sv.yaml
- locale/filters/user/en.yaml
- locale/filters/user/sv.yaml
- src/components/filters/FilterList.jsx
- src/components/filters/UserFilter.jsx
- src/components/filters/index.js
This PR contains UI for the following new query selections/filters:
* `user`
> New filters

- locale/lists/addressList/en.yaml
- locale/lists/addressList/sv.yaml
- locale/lists/assignedRouteList/en.yaml
- src/components/lists/AddressList.jsx
- src/components/lists/AssignedRouteList.jsx
- src/components/lists/items/AddressListItem.jsx
- src/components/lists/items/AssignedRouteListItem.jsx
- src/components/lists/items/AssignedRouteListItem.scss
- src/components/panes/AssignedRouteVisitsPane.jsx
- src/store/visits.js
- src/utils/location.js
This PR adds assigned route progress information to `AssignedRouteList`.
> Assigned route progress in list

- package.json
- src/client/main.js
- src/components/misc/Avatar.jsx
- src/server/app.js
- src/store/index.js
This PR migrates to the new Zetkin SDK with OAuth support.
> New zetkin SDK

- src/components/misc/importer/ImporterTable.scss
- src/components/misc/importer/ImporterTableBody.scss
- src/components/misc/importer/ImporterTableRow.scss
> Fix heightproblem in FireFox

- src/components/panes/SelectPeoplePane.jsx
> Add pagination to SelectPeoplePane

- package.json
- src/server/app.js
Depends on upgrades to Platform coming in R13.
> Require level 2 authentication (TFA)

- package.json
- src/client/main.js
- src/server/app.js
This PR includes some basic security chores.
> Security chores

- src/components/panes/ImportActionsPane.jsx
This PR fixes rendering of activity/location in imported actions list
> Labels after action import

- src/components/misc/importer/ImporterTable.scss
- src/components/misc/importer/ImporterTableBody.scss
- src/components/misc/importer/ImporterTableRow.scss
This PR fixes issues introduced by recent changes to importer table.
* Could not use settings section of importer due to overlapping UI
* Tags did not render correctly
Fixes #814
> Fix bug in importer UI

- locale/forms/callAssignment/en.yaml
- locale/forms/callAssignment/sv.yaml
- locale/forms/personTag/en.yaml
- locale/forms/personTag/sv.yaml
- src/components/forms/CallAssignmentForm.jsx
- src/components/forms/PersonTagForm.jsx
This PR adds two UI features which correlate to recent additions to the Platform API, both related to privacy during phonebanking.
> Phonebanking privacy

- locale/panes/allCampaigns/en.yaml
- src/actions/actionResponse.js
- src/actions/index.js
- src/components/panes/ActionPane.jsx
- src/components/panes/ImportActionsPane.jsx
- src/store/actionResponses.js
- src/utils/import.js
This PR contains a number of minor improvements, including:
* Add tiny feature to remove action responses. Fixes #772
* Fix misspelling in campaign list. Undocumented
* Fix bug causing action import to crash. Fixes #812
* Shorten dates in action import pane
> Minor improvements

- src/components/lists/List.jsx
- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ListItem.jsx
- src/store/actionResponses.js
- src/store/participants.js
This PR implements lazy-loading support in lists, and uses that feature to lazy-load action participants and responses in `ActionList`.
> Lazy-loaded lists

- src/components/panes/MergePeoplePane.jsx
- src/server/api/duplicates.js
Fixes issues regarding surrounding whitespace in people merges. 
Fixes #799  
Fixes #800
> Whitespaces during people merge

- locale/forms/campaign/en.yaml
- locale/forms/campaign/sv.yaml
- locale/lists/campaignList/en.yaml
- locale/lists/campaignList/sv.yaml
- locale/panes/allCampaigns/en.yaml
- src/components/forms/CampaignForm.jsx
- src/components/lists/items/CampaignListItem.jsx
This PR adds features to control and inspect campaign visibility (hidden/open).
Closes #828
> Campaign visibility

- locale/panes/callAssignment/en.yaml
- locale/panes/callAssignment/sv.yaml
- src/components/panes/CallAssignmentPane.jsx
> Hide queue details for huge assignments

- locale/filters/callHistory/en.yaml
- locale/filters/callHistory/sv.yaml
- locale/panes/query/en.yaml
- locale/panes/query/sv.yaml
- src/components/filters/CallHistoryFilter.jsx
- src/components/filters/CallHistoryFilter.scss
- src/components/panes/QueryPane.jsx
This PR adds a new attribute to the `CallHistoryFilter` query filter UI, and localizes some strings that were previously hard-coded.
> Query improvements

- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ActionListItem.scss
- src/store/actions.js
> add loading indicator to aciotn list item

- src/components/lists/List.jsx
- src/components/lists/items/CallAssignmentListItem.jsx
> Lazy load CallAssignmentListItem

- src/components/App.jsx
- src/components/App.scss
- src/scss/_mixins.scss
See #721 
This PR adds a set of animations to the Dashboard.
They are meant to reacquaint the logged-in user with their Organization, so as to avoid them forgetting which org they're now logged in to.
> Add CSS animation to dashboard

- src/components/App.jsx
- src/components/App.scss
- src/components/lists/List.jsx
This PR contains fixes for a few minor issues that were introduced during today's hackathon.
> Minor bugs from today's hackathon

- locale/bulkOps/en.yaml
- locale/bulkOps/sv.yaml
- locale/lists/actionList/en.yaml
- locale/panes/bulkOp/en.yaml
- locale/panes/bulkOp/sv.yaml
- src/components/lists/ActionList.jsx
- src/components/lists/ActionList.scss
- src/components/lists/List.jsx
- src/components/lists/List.scss
- src/components/lists/PersonList.scss
- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ActionListItem.scss
- src/components/lists/items/ListItem.scss
- src/components/lists/items/elements/ParticipantList.scss
- src/components/sections/campaign/AllActionsPane.jsx
- src/server/api/bulk.js
This PR implements bulk operations for action, including one operation to export basic action info as an Excel file.
This accommodates the most urgent requirements of #537, even though it's not quite what was first envisioned for that feature request.
> Export action info

- src/components/App.jsx
- src/components/App.scss
- src/scss/_mixins.scss
This PR tweaks timing and motion of intro animation.
> Intro tweaks

- src/components/misc/personcollection/items/PCActionResponseItem.jsx
> Correct timestamps in action pane

- package.json
- src/components/lists/ActionList.jsx
- src/components/lists/List.jsx
- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ListItem.jsx
- src/components/sections/campaign/AllActionsPane.jsx
- src/store/actionResponses.js
- src/store/actions.js
- src/store/index.js
- src/store/participants.js
This PR contains changes to the `List` infrastructure which allows for items to have secondary data (from the store) without having to individually `connect()`, by passing props from the list.
It also implements this new feature for `ActionList` to avoid having to execute all `connect()` functions each time the state changes.
Fixes #877
> List optimization

- src/components/sections/campaign/AllActionsPane.jsx
> show loading indicator in all actions pane

- src/components/misc/PersonSelectWidget.jsx
- src/components/misc/PersonSelectWidget.scss
- src/components/misc/personcollection/PersonCollection.jsx
- src/components/misc/personcollection/PersonCollection.scss
- src/components/panes/ActionPane.jsx
- src/scss/_mixins.scss
- src/utils/store.js
This PR improves the `PersonSelectWidget` and uses it instead of opening `SelectPeoplePane` in all occurrences of `PersonCollection`.
The PR also fixes a few minor, undocumented issues.
Fixes #872
> Easier selection of persons

- locale/panes/bulkOp/en.yaml
- locale/panes/bulkOp/sv.yaml
- src/components/bulk/config/ActionExportBulkOpConfig.scss
Minor language and styling tweaks.
> Tweak cap message in ActionExportBulkOpConfig

- src/actions/search/procs.js
- src/components/panes/ActionDayPane.jsx
This bug fixes two issues related to the `ActionDayPane`, and searching to find it. See commit log for details.
> Action day search fixes

- src/components/misc/PersonSelectWidget.jsx
- src/components/misc/personcollection/PersonCollection.jsx
- src/components/panes/ActionPane.jsx
- src/store/participants.js
This PR adds two improvements to the `ActionPane` and some minor changes to related components. See commit log for details.
> Action pane improvements

- src/components/misc/timeline/renderers/ActionTimelineEvent.jsx
- src/components/misc/timeline/renderers/MultiActionTimelineEvent.jsx
- src/components/panes/ActionDayPane.jsx
- src/components/panes/EditQueryPane.jsx
- src/components/sections/Section.jsx
- src/utils/PaneManager.js
This PR fixes four minor documented issues and one undocumented issue. See commit log for details.
> Misc issues

- src/actions/bulk.js
- src/components/panes/BulkOpPane.jsx
- src/store/people.js
> bulk operations pending

- src/server/api/bulk.js
> alt phone in export

- locale/filters/random/da.yaml
- locale/filters/random/en.yaml
- locale/filters/random/sv.yaml
- src/components/filters/FilterList.jsx
- src/components/filters/RandomFilter.jsx
- src/components/filters/RandomFilter.scss
This PR adds the following to the Random Filter:
- The ability to swap between two units. `People`, `Percent`
- A button for randomizing the output via seed generation.
- An amount cap of 99 if the unit is set to `Percent`.
- Corresponding locale mappings. (In need of review)
Implements #404
> Feature/random filters#404

- src/components/lists/AddressList.scss
- src/components/lists/CallAssignmentList.scss
- src/components/lists/CallList.scss
- src/components/lists/CanvassAssignmentList.scss
- src/components/lists/items/AddressVisitListItem.scss
- src/components/lists/items/CallAssignmentListItem.scss
- src/components/lists/items/CallListItem.scss
- src/components/lists/items/CanvassAssignmentListItem.scss
- src/components/lists/items/ListItem.scss
- src/components/misc/ProgressBar.scss
- src/components/sections/RootPaneBase.scss
- src/components/sections/campaign/AllActionsPane.scss
This PR adds responsive styling to Dialog - Assignments and Call log and also Canvass - Assignments and Visit Log.
+ I also added display none to the span with text (old actions) in Actions so that it don't show on smaller screens.
> Mobile Interface Dialog Styling

- src/components/panes/ActionPane.jsx
- src/components/panes/ActionPane.scss
> Add campaign to ActionPane and change activity icon

- locale/panes/query/en.yaml
- src/components/panes/QueryPane.jsx
- src/components/panes/QueryPane.scss
> Add item to summary, refreshing query results on click

- src/actions/search/index.js
- src/actions/search/utils.js
- src/components/KeyboardShortcuts.jsx
- src/components/forms/inputs/RelSelectInput.jsx
- src/components/header/search/ScopeSelect.jsx
- src/components/header/search/Search.jsx
- src/components/misc/PersonSelectWidget.jsx
- src/store/search.js
Refactor search store to handle multiple searches. 
Refactor PersonSelectWidget to use search API to retrieve people.
Related to #970
> Refactor search store to handle multiple searches

- src/components/filters/CallHistoryFilter.jsx
> Fix exception in call history filter

- src/components/lists/List.jsx
- src/components/lists/items/ActionListItem.jsx
Fixes #969 
(See issue ticket for details)
> Fix bug in ActionList lazy loading

- src/components/misc/PersonSelectWidget.jsx
> Clear search on PersonSelectWidget unmount

- src/store/queries.js
> Fix EditQueryPane closing on adding smart search query

- bin/run_dev
- env/app/Dockerfile
This PR fixes two issues with the development environment. See commit log for details.
> Development environment issues

- src/components/misc/tagcloud/TagCloudItem.jsx
> Tag description tooltip

- locale/panes/selectPersonTags/en.yaml
- locale/panes/selectPersonTags/sv.yaml
- src/components/panes/SelectPersonTagsPane.jsx
- src/components/panes/SelectPersonTagsPane.scss
> Filter SelectPersonTagsPane tags

- locale/panes/selectPersonTags/en.yaml
- locale/panes/selectPersonTags/sv.yaml
- src/components/forms/inputs/TextInput.jsx
- src/components/panes/SelectPersonTagsPane.jsx
This PR adds an optional `placeholder` prop to `TextInput` and adds a placeholder text to the `SelectPersonTagsPane` filter.
> SelectPersonTagsPane filter placeholder

- src/components/panes/ImportActionsPane.scss
>  ImportActionsPane selects width overflow bugfix

- src/components/panes/CallPane.jsx
> CallPane infinite dispatch loop bugfix

- src/actions/surveySubmission.js
Fixes issue where filtering on linked/unlinked SurveySubmission always return unlinked submissions.
Closes #1040
> Fix SurveySubmission filtering bug

- locale/panes/import/en.yaml
- locale/panes/import/sv.yaml
- src/actions/importer.js
- src/components/misc/importer/ImporterColumnHead.jsx
- src/components/misc/importer/settings/PersonGenderColumnSettings.jsx
- src/components/misc/importer/settings/index.js
- src/components/misc/importer/values/PersonGenderColumnValue.jsx
- src/components/misc/importer/values/index.js
Implementation of mapping of the gender field on import.
Resolves #350
> Gender import field

- locale/forms/action/en.yaml
- locale/forms/action/sv.yaml
- src/components/forms/ActionForm.jsx
- src/components/lists/items/ActionListItem.jsx
- src/components/misc/actioncal/ActionItem.jsx
- src/components/panes/ActionPane.jsx
Add title field to ActionForm, ActionPane, ActionItem, ActionListItem
> Add title field to Action

- env/app/Dockerfile
Update the version of the base image and update to node 10.0
> Update phusion image and node version

- .gitignore
- src/client/main.js
- src/server/locale.js
Add Norwegian locale. There are no strings for Organize yet, but the locale needs to be recognized, and the English fallback used, which is the case with this PR.
Relevant to #1067
> Norwegian locale

- src/actions/actionImport.js
- src/store/actionImport.js
> Fix action import bug caused by CSV import feature

- locale/filters/personData/en.yaml
- locale/filters/personData/sv.yaml
- locale/forms/person/en.yaml
- locale/forms/person/sv.yaml
- locale/panes/confirmImport/en.yaml
- locale/panes/confirmImport/sv.yaml
- locale/panes/import/en.yaml
- locale/panes/import/sv.yaml
- locale/panes/mergePeople/en.yaml
- locale/panes/mergePeople/sv.yaml
- src/components/filters/PersonDataFilter.jsx
- src/components/forms/PersonForm.jsx
- src/components/misc/importer/ImporterColumnHead.jsx
- src/components/misc/importer/settings/PersonDataColumnSettings.jsx
- src/components/panes/ConfirmImportPane.jsx
- src/components/panes/MergePeoplePane.jsx
- src/components/panes/PersonPane.jsx
- src/server/api/bulk.js
> Add country field to person

- src/store/view.js
> Prevent opening two identical panes

- src/components/panes/EditCampaignPane.jsx
- src/components/panes/EditCampaignPane.scss
This PR adds a link to the campaign in the Activist Portal to the `EditCampaignPane`.
Supersedes #1083
> Campaign link in EditCampaignPane

- src/components/forms/CampaignForm.jsx
> Hide campaign visibility select when campaign is not published

- .gitattributes
- README.md
Very minor edit. Also a .gitattributes that should take care of LF/CRLF-convertion problems.
> Use SSH to clone, not HTTPS

- src/components/lists/items/ActionListItem.jsx
- src/components/lists/items/ActionListItem.scss
> Indicate 2x participant count with darker color

- gulpfile.js
- src/components/header/OrgPicker.jsx
- webpack.config.js
This PR fixes issues with the build, some of which were introduced by #1093 for Windows developers.
Since the changes in #1093 have since been deemed unnecessary (in favor of a WSL2 workflow described in our [Windows guide](https://developer.zetkin.org/contributing/windows)) they can be safely reverted as is done in this PR.
> Fix build issues

- src/components/panes/EditCallerPane.jsx
- src/components/panes/EditCallerPane.scss
Fixes #829 (credit also to Sam McMurray)
> Edited styling for the caller tabs title

- src/components/panes/AddPersonTagPane.jsx
- src/components/panes/EditPersonTagPane.jsx
> fixed bug where allowed edit person tag title to be empty

- src/components/panes/JoinSubmissionPane.scss
> Fix an undocumented layout issue in JoinSubmissionPane

- locale/panes/import/en.yaml
- locale/panes/import/sv.yaml
- package.json
- src/components/misc/importer/ImporterColumnHead.jsx
- src/components/misc/importer/values/DateColumnValue.jsx
- src/components/misc/importer/values/index.js
- src/components/panes/ConfirmImportPane.jsx
- src/utils/getDate.js
Better date parsing in import, including parsing birthdays from ID numbers. Add DateColumnValue class so that users can see what date will be interpreted from the imported data.
Also fixes #1128
> Better date parsing in import

- src/components/forms/PersonForm.jsx
- src/components/forms/inputs/InputBase.jsx
- src/components/panes/AddPersonPane.jsx
- src/components/panes/EditPersonPane.jsx
This PR adds custom fields to `PersonForm` in both `AddPersonPane` and `EditPersonPane`. This means that values for custom fields can now be set/reset the same way that values for "native" person fields.
Closes #1122
> Custom Fields in PersonForm

- locale/filters/personTags/en.yaml
- locale/filters/personTags/sv.yaml
- src/components/filters/PersonTagsFilter.jsx
Implements some filter for tags for specifying minimum number of tags in search.
> some filter for person_tags

- src/components/App.jsx
- src/components/misc/GoogleAnalytics.jsx
- webpack.config.js
This PR adds the "new" Google Analytics (GA4) tracking code, which is externalized to an environment variable. It also adds more versatile titles (`<title>`) to sections and sub-sections. This is good for many reasons, but motivated here because they show up nicer in Google Analytics.
Provides a baseline of functionality required by #1141
> Better Google Analytics

- locale/panes/joinSubmission/en.yaml
- src/actions/joinForm.js
- src/components/sections/RootPaneBase.jsx
- src/components/sections/people/JoiningPane.jsx
- src/components/sections/people/JoiningPane.scss
- src/store/joinForms.js
> Filtering and paging of Join Forms

- src/components/panes/AddViewColumnPane.jsx
> Sort tags alphabetically in AddViewColumnPane

- src/components/misc/personViews/PersonViewTable.jsx
Fixes undocumented bug, to be deployed immediately.
> Sort before paginating in large views

- src/components/misc/personViews/PersonViewAddRow.scss
- src/components/misc/personViews/PersonViewTable.jsx
- src/components/misc/personViews/PersonViewTable.scss
> PersonViewAddRow visible before rows are populated

- src/components/panes/ConfirmImportPane.jsx
Fixes #1219 by converting any non-string to string in import validation.
I cannot reproduce the error however, so this is a highly theoretical fix.
> Fix validation error

- src/actions/index.js
- src/actions/personTag.js
- src/components/panes/EditPersonTagPane.jsx
- src/store/people.js
- src/store/personTags.js
> Delete person tag

- src/components/misc/personViews/PersonViewTable.jsx
This PR cleans up unused variables.
Paired with @oelrich
> Drop unused variables

- src/components/panes/EditGroupPane.jsx
- src/components/panes/EditLocationTagPane.jsx
- src/components/panes/EditPersonTagPane.jsx
- src/components/panes/EditQueryPane.jsx
- src/components/panes/EditViewColumnPane.jsx
Resolves #1149. Have not been able to test fully
> Edited getValues to getChangedValues

- src/components/lists/PersonQueryList.jsx
- src/components/lists/PersonTagList.jsx
- src/components/sections/people/PersonViewsPane.jsx
This PR implements A-Z sorting in different places.
We used JS sorting for some things, and options in React Component elsehwere.
See #1161
Paired with @oelrich!
> PersonTagList, PersonQueryList, PersonViewsPane: A-Z order

- locale/panes/personViews/en.yaml
- src/components/forms/inputs/RelSelectInput.jsx
- src/components/forms/inputs/RelSelectInput.scss
- src/components/sections/people/PersonViewsPane.jsx
- src/components/sections/people/PersonViewsPane.scss
> Collapse view header

- src/components/misc/personViews/PersonViewTable.jsx
> Bug/entry level/sort survey response

- src/components/forms/Form.jsx
> Disable autocomplete on forms

- locale/misc/personViewTable/en.yaml
- locale/panes/addViewColumn/en.yaml
- src/components/misc/personViews/PersonViewTableRow.jsx
- src/components/misc/personViews/cells/GenderViewCell.jsx
- src/components/panes/AddViewColumnPane.jsx
> Add gender view column to available options and a gender view cell

- locale/misc/fields/en.yaml
- src/components/panes/JoinSubmissionPane.jsx
> Render gender properly in JoinSubmissionPane

- src/store/personViews.js
> Update view when relevant person object updated

- src/components/forms/inputs/RelSelectInput.jsx
- src/components/misc/PersonSelectWidget.jsx
…-side fuzzy loading, fixes #1246
> Allows fuzzy loading of names

- locale/panes/confirmDelete/en.yaml
- locale/panes/confirmDelete/sv.yaml
- locale/panes/editPerson/en.yaml
- locale/panes/editPerson/sv.yaml
- src/actions/connection.js
- src/actions/index.js
- src/components/panes/ConfirmDeletePane.jsx
- src/components/panes/ConfirmDeletePane.scss
- src/components/panes/EditPersonPane.jsx
- src/components/panes/EditPersonPane.scss
- src/store/connections.js
- src/store/index.js
- src/store/people.js
- src/store/view.js
Implement interface for disconnecting a person instead of deleting.
> Disconnect person instead of deleting

- src/components/header/OrgPicker.scss
- src/components/header/OrgUserMenu.scss
Add scrollbar to organization picker.
> Orgpicker scrollbar

- package.json
This PR updates the express middleware and Zetkin SDK libraries to their recent releases which contain the features necessary to work with two-factor authentication on the new API gateway.
> Upgrade Zetkin SDK and express middleware libraries

- src/components/filters/CallHistoryFilter.jsx
- src/components/filters/FilterTimeFrameSelect.jsx
> Fix reset of timeframe dates

- locale/panes/personViews/en.yaml
- src/actions/personView.js
- src/components/sections/people/PersonViewsPane.jsx
- src/components/sections/people/PersonViewsPane.scss
Implement copy of views. This copies the view, the columns, and the rows.
Not yet implemented: copy of local values.
> Implement copy of person views

- src/server/datarouter.js
> Redirect ?org requests to current path, not /

- locale/forms/survey/en.yaml
- locale/forms/survey/sv.yaml
- locale/lists/surveyList/en.yaml
- locale/lists/surveyList/sv.yaml
- locale/panes/survey/en.yaml
- locale/panes/survey/sv.yaml
- src/actions/survey.js
- src/components/forms/SurveyForm.jsx
- src/components/lists/SurveyList.jsx
- src/components/lists/SurveyList.scss
- src/components/lists/items/SurveyListItem.jsx
- src/components/lists/items/SurveyListItem.scss
- src/components/panes/SurveyPane.jsx
- src/components/panes/SurveyPane.scss
> Make it possible to archive a survey

- src/components/panes/SelectPersonTagsPane.jsx
> Fix select tag from specific organization bug

- locale/forms/survey/en.yaml
- locale/forms/survey/sv.yaml
- locale/panes/survey/en.yaml
- locale/panes/survey/sv.yaml
- src/components/forms/SurveyForm.jsx
- src/components/panes/SurveyPane.jsx
- src/components/panes/SurveyPane.scss
- src/components/sections/survey/SurveyListPane.jsx
Resolves #1298 
Make it possible to set the org_access field and indicate if the organization is shared and if it is owned by another organization.
> Shared surveys

- src/utils/filterByOrg.js
> Fix bug where anestors queries are not available to suborg query filter

- src/components/filters/UserFilter.jsx
Fix missing component in UserFilter which causes a crash when trying to create a user filter.
> Fix missing component in UserFilter

- locale/filters/subQuery/en.yaml
- locale/filters/subQuery/sv.yaml
- src/components/filters/SubQueryFilter.jsx
New filter option for subQuery in/notin operator.
> Filter option for new subQuery operator.

- src/components/filters/SurveyOptionFilter.jsx
Fixes #1310
Serious bug, this should be pushed as soon as possible IMO!
> Fix query survey option bug

- src/server/api/bulk.js
Resolves #1308 
I'm not quite satisfied with the format of the resulting Excel-sheet, but it works. The problem is that it doesn't fit on a single printed page. Another solution could be to do a sub-section between each action row with a header for the participant contact info, but it seems that formatting is int the "pro"-version of the xlsx-package so I'm not sure how to make it more presentable and clear.
> Add participants to the action export excel sheet

- locale/forms/surveyQuestion/en.yaml
- locale/forms/surveyQuestion/sv.yaml
- src/components/forms/SurveyQuestionForm.jsx
- src/components/misc/surveyOutline/SurveyOutlineElement.jsx
- src/components/misc/surveyOutline/SurveyOutlineElement.scss
- src/components/panes/AddSurveyQuestionPane.jsx
- src/components/panes/EditSurveyQuestionPane.jsx
Add visibility to survey question form and indicate whether an element is visible or not.
> Add visibility to survey question

- locale/panes/addViewColumn/en.yaml
- src/components/misc/personViews/PersonViewTable.scss
- src/components/misc/personViews/PersonViewTableRow.jsx
- src/components/misc/personViews/cells/SurveyOptionsCell.jsx
- src/components/misc/personViews/cells/SurveyOptionsCell.scss
- src/components/panes/AddViewColumnPane.jsx
This appears to work but is untested with multiple options and the styling is not great. It also concatenates all (unique) options from all submissions, I don't know if this is the best choice or not. Needs some further work.
> Survey options view column

- src/actions/action.js
- src/actions/actionImport.js
- src/components/fullpages/ActivistPage.jsx
Resolves #1323 
Resolves #1322
> Set published to yesterday at 00:00 when creating a new action
