zetkin/organize.zetk.in

src/js/server/app.js

The data router should be hit last, to avoid hitting the API when retrieving
static files, favicon.ico, the API (feedback) and things like that.

Refactor to avoid reduntant API hits

---

src/js/actions/search.js
src/js/components/KeyboardShortcuts.jsx
src/js/components/header/search/ScopeSelect.jsx
src/js/components/header/search/Search.jsx
src/js/server/search.js
src/js/stores/search.js
src/scss/header/_base.scss

This implements scoped search, i.e. searching for only a single category of content, e.g. maps content, people or campaign content. It adds a widget to the search form for changing the scope and keyboard shortcuts for focusing the search field with a predefined scope.

Scoped search

---

package.json
src/js/components/panes/PaneBase.jsx
src/js/utils/PaneManager.js
src/scss/_base.scss
src/scss/_medium.scss
src/scss/header/_base.scss
src/scss/section/_base.scss
src/scss/section/_medium.scss

On devices with narrow screens the horizontal pane layout does not work. This PR creates a layout for narrow screens, where panes are stacked vertically and can no longer be dragged around. Scrolling in this layout is not managed, but instead relies on browser scrolling which is both easier to implement and will likely work better on devices with narrow screens (which tend to be slower).
The screenshot shows a (contrived) situation where six panes have been stacked on top of eachother in this new vertical layout. It will be possible to jump back in the stack by tapping the name of an underlying pane.

Vertical (mobile) pane layout

---

src/js/server/datarouter.js

There was a lot of boilerplate involved in preloading data for every route, even though they essentially all did the exact same thing; execute one or several actions and invoke next() when it finished. The new waitForActions() function does this and makes the code much shorter. 
This PR also adds previously missing preloaders for people and locations.

Better preloading

---

src/js/components/fullpages/ActivistPage.jsx
src/js/server/app.js
src/js/server/datarouter.js
src/js/stores/user.js

Users that do not have an official role in any organization should should not be able to access the organizer interface. This PR addss a check in the data router and redirects any such user to a special information page at /activist.
A nice design and copy still needs to be created for the /activist page.

Handle non-officials

---

env/app/run.sh

A developer who already has all dependencies locally shouldn't have to install
them inside the container too.

Avoid npm (re-)install

---

src/js/components/header/UserMenu.jsx
src/js/server/authrouter.js
src/js/stores/search.js
src/js/stores/user.js

Instead of hardcoding URLs to other parts of the app, this derives the hosts
from dynamic sources such as window.location and process.env.

Dynamic URLs

---

src/js/components/misc/actioncal/ActionCalendar.jsx
src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/misc/actioncal/ActionItem.jsx
src/js/components/misc/actioncal/ActionWeek.jsx
src/js/components/panes/AddActionPane.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/stores/action.js
src/js/utils/PaneUtils.js
src/js/utils/polyfills.js
src/scss/actioncal/_medium.scss
src/scss/panes/_medium.scss
src/scss/section/_base.scss
src/scss/section/_medium.scss
src/scss/style.scss

Creates a component to display actions in a calendar and adds it as a second view mode to the "All actions" sub-section.
The `ActionCalendar` component is completely "dumb", displays all actions that are given to it (assuming that they are ordered correctly), allows clicking on an action to "open" (or whatever the parent component dictates) and supports drag and drop between days.

Campaign calendar view

---

src/js/components/App.jsx
src/js/components/misc/campaignplayer/CampaignPlayer.jsx
src/js/components/misc/campaignplayer/Scrubber.jsx
src/js/components/misc/campaignplayer/Transport.jsx
src/js/components/panes/AddLocationPane.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/js/components/sections/campaign/CampaignSection.jsx
src/js/server/datarouter.js
src/js/stores/location.js
src/scss/campaignplayer/_base.scss
src/scss/style.scss

This PR creates a CampaignPlayer component and a sub-section in the Campaign section to host it.
The CampaignPlayer takes a list of actions and play them back as a heatmap over time. The player can be started and stopped, and the playback can be scrubbed back and forth using a slider.

Campaign playback

---

src/js/components/misc/actionlocations/ActionLocationItem.jsx
src/js/components/misc/actionlocations/ActionLocations.jsx
src/js/components/misc/actionlocations/DayCycleGraph.jsx
src/js/components/sections/campaign/CampaignLocationsPane.jsx
src/js/components/sections/campaign/CampaignSection.jsx
src/js/server/datarouter.js
src/scss/actionlocations/_base.scss
src/scss/actionlocations/_medium.scss
src/scss/panes/_medium.scss
src/scss/section/_medium.scss
src/scss/style.scss

Adds a sub-section under Campaigns which displays information about the distribution of actions across locations. Each location is a card with the name and total number of actions displayed, as well as a breakdown of the ratio between different times of day (morning, noon, afternoon, evening, night).

Campaign locations

---

src/js/actions/action.js
src/js/actions/participant.js
src/js/components/dashboard/Dashboard.jsx
src/js/components/misc/LocationMap.jsx
src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/misc/actioncal/ActionItem.jsx
src/js/components/misc/actioncal/ActionMiniCalendar.jsx
src/js/components/misc/actionlocations/ActionLocationItem.jsx
src/js/components/misc/actionlocations/ActionLocations.jsx
src/js/components/misc/actionlocations/DayCycleGraph.jsx
src/js/components/misc/campaignplayer/CampaignPlayer.jsx
src/js/components/panes/PaneBase.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/components/sections/campaign/CampaignLocationsPane.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/js/components/sections/campaign/PaneWithCalendar.jsx
src/js/server/search.js
src/js/stores/action.js
src/js/stores/participant.js
src/js/stores/person.js
src/js/stores/user.js
src/js/utils/PaneManager.js
src/js/utils/polyfills.js
src/scss/actioncal/_medium.scss
src/scss/panes/_medium.scss

This creates a miniature calendar component, to be used at the top of various campaign panes, and adds it specifically to the sub-sections "Campaign locations" and "Playback".
The PR also implements highlighting of actions in the mini-calendar, and logic to toggle the highlight based on mouse-interaction with the ActionLocations component. It's now possible to hover a location (or a time-of-day bar) in the "Campaign locations" section and get feedback of relevant actions in the new
mini-calendar.

Campaign mini-calendar

---

package.json
src/js/actions/action.js
src/js/components/forms/ActionForm.jsx
src/js/components/forms/Form.jsx
src/js/components/forms/inputs/DateInput.jsx
src/js/components/forms/inputs/IntInput.jsx
src/js/components/forms/inputs/RelSelectInput.jsx
src/js/components/forms/inputs/TimeInput.jsx
src/js/components/misc/actioncal/ActionCalendar.jsx
src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/panes/AddActionPane.jsx
src/js/components/panes/PaneBase.jsx
src/js/components/sections/campaign/PaneWithCalendar.jsx
src/js/stores/action.js

This adds a pane to create actions. It also implements a bunch of logic around this cause, and improves the pre-existing ActionForm with better widgets.
Clicking add in a calendar will pre-fill the date and time. And if a campaign was already selected in the interface, that campaign will be pre-selected in the action pane as well.

Add action pane

---

src/js/components/forms/ActionForm.jsx
src/js/components/forms/inputs/RelSelectInput.jsx
src/js/components/panes/AddActionPane.jsx
src/js/components/panes/AddActivityPane.jsx
src/js/components/panes/AddCampaignPane.jsx
src/js/components/panes/AddLocationPane.jsx
src/js/components/panes/EditActionPane.jsx
src/js/components/panes/PaneBase.jsx
src/js/components/sections/SectionBase.jsx
src/scss/inputs/_base.scss
src/scss/style.scss

This is a total revamp of the RelSelectInput component, the purpose of which is to let a user select between a list of objects (e.g. choose the location for an action or the manager (person) of a campaign).
This used to be a simple `<select>` but is now a custom widget which allows you to filter/search for the object you want, navigate with your up/down keys and create a new object if you cannot find what you're looking for.
Selecting the "create" option invokes a callback which can be used to open the relevant add pane. This PR implements this logic for locations, activities and campaigns in the panes containing an `ActionForm`.

Better RelSelectInput

---

src/js/components/App.jsx
src/js/components/header/Header.jsx
src/js/components/header/search/CampaignMatch.jsx
src/js/components/header/search/LocationMatch.jsx
src/js/components/header/search/MatchBase.jsx
src/js/components/header/search/PersonMatch.jsx
src/js/components/header/search/Search.jsx
src/js/components/sections/SectionBase.jsx
src/scss/header/_base.scss

This PR improves the search results in the live search. It adds some styling to make them look and feel nicer, but mostly it revamps the way matches are opened so that they are (when possible) opened in the current context, i.e. with all open panes intact. This allows the user to search and open something while
working on something else, without having to go back and forth.
To achieve this, some changes to the way panes work had to be made, as described in the commits and code comments.

Better search results

---

src/js/components/misc/actioncal/ActionCalendar.jsx
src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/misc/actioncal/ActionMiniCalendar.jsx
src/js/components/panes/ActionDayPane.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/components/sections/campaign/CampaignLocationsPane.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/js/components/sections/campaign/PaneWithCalendar.jsx
src/js/utils/PaneUtils.js
src/scss/actioncal/_medium.scss

Creates a pane that displays the actions on a specific date, to be opened mainly from calendar views. The new pane renders the actions using the regular `ActionList` component.

Action day pane

---

src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/misc/actioncal/ActionDayOverflow.jsx
src/js/components/misc/actioncal/ActionMiniCalendar.jsx
src/scss/actioncal/_medium.scss

When there are more actions in a day than can nicely be shown in a calendar day, the overflow (i.e. number of actions) will be displayed in a separate box which can be clicked to open the ActionDayPane.
In the mini-calendar, the special box will highlight just like normal actions when there are one or more highlight actions. In these cases, the number will instead display the number of highlights.

Display overflow in calendar days

---

package.json
src/js/components/header/search/ActionDayMatch.jsx
src/js/components/header/search/Search.jsx
src/js/server/search.js
src/js/utils/polyfills.js

Implements searching for dates, returning actions on that date as a single match linking to the relevant date in `ActionDayPane`. The sugar.js library is used for input, meaning that we support "natural language input", e.g. on top of just numeric dates also things like "july 1" "tomorrow" and "next thursday".
Closes #100 if merged.

Search for date

---

src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/misc/actioncal/ActionItem.jsx
src/js/components/misc/actioncal/ActionMiniCalendar.jsx
src/scss/actioncal/_medium.scss

This PR contains several minor improvements to the look and feel of the `ActionCalendar` and `ActionMiniCalendar` components.
* General styling improvements
* Add time label to action items
* Hover-effect on days when dragging an action over it
* Fix bug related to display cap on number of actions in a day
* CSS transitions for when an action is added to and removed from a day
* Highlight today

Action calendar look & feel

---

package.json
src/js/components/misc/actioncal/ActionCalendar.jsx
src/js/components/misc/actioncal/ActionDay.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/components/sections/campaign/PaneWithCalendar.jsx
src/scss/actioncal/_medium.scss

This adds the possibility to clone actions instead of moving them by holding shift while dragging and dropping. This required some changes to the react-dnd library, for which we now have [our own fork](https://github.com/zetkin/react-dnd) (including it's [dnd-core requirement](https://github.com/zetkin/dnd-core)).
When dragging over a day, a small hint at the bottom of the day grid square instructs the user to hold shift to clone.
Closes #97.

Drag to clone action

---

src/js/stores/action.js

This PR creates a new `sortActions()` function which includes the ID as a secondary sort field after `start_time`, so that two actions starting on the same time will remain stable when sorting and re-sorting.
Fixes #113

Improve stability of action sorting

---

src/js/actions/query.js
src/js/components/filters/CampaignFilter.jsx
src/js/components/filters/FilterBase.jsx
src/js/components/filters/JoinDateFilter.jsx
src/js/components/filters/PersonDataFilter.jsx
src/js/components/filters/index.js
src/js/components/forms/inputs/RelSelectInput.jsx
src/js/components/header/search/ActionDayMatch.jsx
src/js/components/header/search/QueryMatch.jsx
src/js/components/header/search/Search.jsx
src/js/components/panes/EditQueryPane.jsx
src/js/components/panes/QueryPane.jsx
src/js/components/sections/people/PeopleListPane.jsx
src/js/flux.js
src/js/stores/query.js
src/js/stores/search.js
src/js/utils/PaneUtils.js
src/scss/filters/_base.scss
src/scss/inputs/_base.scss
src/scss/panes/_medium.scss
src/scss/style.scss

This PR creates a framework for setting up complex person queries by chaining different kinds of filters. It creates some basic filters (some of which are noops simply for demo purpose at this point), and an `EditQueryPane` for adding and configuring filters into a query.
The PR also implements searching for stored queries and opening their results in a separate `QueryPane`, so that you can search for example for a cadre shortlist to more easily find people who are easy to engage in one of tomorrow's actions. Although not yet implemented in `PeopleList` (#133), it should be possible to drag people directly from this shortlist onto an action to book them.
Closes #111

Person query framework

---

src/js/components/misc/DraggableAvatar.jsx
src/js/components/misc/peoplelist/PeopleListItem.jsx
src/js/components/panes/PersonPane.jsx

This create a separate `DraggableAvatar` component which takes care of the `DragSource` setup itself, so that it doesn't have to be implemented separately in every use case. This new component is now used in the `PeopleList` so that avatars can be dragged straight from the list without opening a `PersonPane`.

Draggable avatar

---

src/js/components/panes/QueryPane.jsx

Always re-load people when opening a new `QueryPane`.
Fixes #135

Load people in QueryPane

---

src/js/components/misc/actioncal/ActionCalendar.jsx

When a campaign started on a Sunday, the calendar would render from the following Monday (instead of the previous) resulting in no actions being rendered because it never found the correct date for the first one in the loop.

Fix issue with actioncalendar not rendering properly

---

src/js/components/misc/actioncal/ActionMiniCalendar.jsx

Scroll `ActionMiniCalendar` horizontally even when using the wheel to scroll vertically. This just feels more natural, since the calendar can't be scrolled vertically anyway.
Closes #140.

Mini-calendar scrolling

---

src/js/components/forms/inputs/RelSelectInput.jsx
src/js/components/misc/CampaignSelect.jsx
src/js/components/sections/campaign/ActionDistributionPane.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/components/sections/campaign/CampaignOverviewPane.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/js/components/sections/campaign/CampaignSectionPaneBase.jsx

This PR uses the `RelSelectInput` component in `CampaignSelect` to allow for adding and editing campaigns from that box. It also adds the possibility for null options to `RelSelectInput`.
Closes #146.

Use RelSelectInput for campaign filter

---

src/scss/header/_base.scss
src/scss/header/_medium.scss

This is just a dummy beta label that doesn't really mean anything. Zetkin is not beta. However, it serves as a reminder to those to whom we demo Zetkin that it's pre-release and should be considered such.
Closes #153.

Add beta label

---

src/js/actions/participant.js
src/js/components/misc/actionlist/ActionList.jsx
src/js/components/misc/elements/Action.jsx
src/js/components/misc/elements/Person.jsx
src/js/components/panes/ActionDayPane.jsx
src/js/components/panes/MoveParticipantsPane.jsx
src/js/components/sections/SectionBase.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/stores/participant.js
src/scss/panes/_medium.scss

This PR contains several improvements to the `MoveParticipantsPane` and code related to moving participants.
* Always open `MoveParticipantsPane` on top and never allow more than one open
* Add individual execute/undo buttons to moves
* Remove undone/executed moves from store, ridding the nead for `clearMoves()`
* Improve styling of `MoveParticipantsPane`
The PR also adds logic to load actions from `ActionDayPane` if the store is empty.
Closes #138.

Better MoveParticipantsPane

---

src/js/components/misc/peoplelist/PeopleList.jsx
src/js/components/misc/peoplelist/PeopleListItem.jsx
src/js/stores/person.js

This PR makes data in the people store pseudo-immutable, by making sure that whenever the people array changes it gets copied. This means that data can be relied upon to not change unless the entire list is replaced, which is used to deduce whether the `PeopleList` and `PeopleListItem` components need to render, in their respective `shouldComponentUpdate()` methods.
Closes #130.

PeopleList optimization

---

src/js/components/header/UserMenu.jsx
src/scss/header/_base.scss
src/scss/header/_medium.scss

This PR tweaks the styling and content of the user menu.
* Show name instead of e-mail address of user
* Show real avatar using the `Avatar` component
* Fade down background when hovering menu to make it pop
Closes #117.

Better user menu

---

src/js/components/forms/inputs/InputBase.jsx
src/js/components/misc/CampaignSelect.jsx
src/js/components/misc/campaignplayer/CampaignPlayer.jsx
src/js/components/misc/campaignplayer/Transport.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/scss/campaignplayer/_base.scss
src/scss/panes/_medium.scss

This PR enhances the campaign player in several ways. It improves the performance by disabling the heavy mini-calendar highlights. It might be possible to add this back once stores are immutable.
The PR also adds a time label to the player transport, and re-styles the entire `CampaignPlaybackPane` with a full-screen map and the transport at the bottom.
This pane will still need to be revisited, and especially the campaign select box, once a new solution for headers has been developed, as discussed in #115.
Closes #125.

Better campaign player

---

src/js/stores/search.js

When stored query searching was implemented this introduced an issue with old
search matches not being properly cleaned out as the search string changed.

Fix search issue with old results lingering

---

src/js/components/misc/Avatar.jsx
src/js/components/misc/elements/Person.jsx

In many cases, a person object will not be a full object but the smaller version available in many relationships. This PR makes sure that `Person` and `Avatar` components handle these cases and still display the correct name, from the `name` attribute instead of the `first_name` and `last_name` attributes.
Fixes #167

Hand Person "name" attribute

---

src/js/components/misc/actioncal/ActionCalendar.jsx
src/js/components/sections/campaign/AllActionsPane.jsx

This PR makes sure that if there are no actions to be shown in `AllActionsPane`, the `ActionCalendar` will be rendered with a default start and end date 31 days apart around today. It also makes sure that even if there are only a few actions, there will still never be less than one month visible.

Never empty ActionCalendar

---

src/js/components/misc/actioncal/ActionDay.jsx
src/scss/actioncal/_medium.scss

Makes the headers smaller and lighter to make them stand out less.

Better header look in ActionDay

---

src/js/components/misc/peoplelist/PeopleList.jsx

A bug in the sort comparison function resulted in wonky, party random sorting.

Fix sorting bug in PeopleList

---

src/js/components/forms/ActionForm.jsx
src/js/components/forms/Form.jsx
src/js/components/forms/inputs/TimeInput.jsx
src/scss/forms/_base.scss
src/scss/inputs/_base.scss

This revamps the `TimeInput` component with custom logic instead of the browser's wonked `<input type="time">`, as discussed in #55. No good date picker was found, so the native will have to do for now.
This PR also lays out the start and end time inputs in the `ActionForm` next to eachother.

Time inputs

---

src/js/components/misc/ViewSwitch.jsx
src/js/components/panes/PaneBase.jsx
src/js/components/sections/SectionBase.jsx
src/js/components/sections/campaign/ActionDistributionPane.jsx
src/js/components/sections/campaign/AllActionsPane.jsx
src/js/components/sections/campaign/CampaignPlaybackPane.jsx
src/js/components/sections/maps/LocationsPane.jsx
src/js/components/sections/people/PeopleListPane.jsx
src/js/utils/PaneManager.js
src/scss/_base.scss
src/scss/actioncal/_medium.scss
src/scss/inputs/_base.scss
src/scss/panes/_medium.scss
src/scss/section/_medium.scss

This PR contains a complete technical and conceptual revamp of the pane headers. It moves tools like view switches, filter selects and add buttons to the new "toolbar", and removes title text from base panes. The header/toolbar looks like regular content, but sticks to the top when scrolling a pane.
Closes #115

Pane header revamp (WIP)

---

src/js/components/panes/PaneBase.jsx
src/js/utils/PaneManager.js
src/scss/dashboard/_medium.scss
src/scss/panes/_medium.scss
src/scss/section/_medium.scss

This PR implements native scrolling for dashboard and all panes, instead of the custom-built scrolling that was implemented in `PaneManager`. It hides the scroll bar though, so that you don't get scrollbars visible on every pane all the time.
This fixes several registered issues. See commit messages for details.

Native, smoother scrolling

---

src/js/components/panes/PaneBase.jsx
src/scss/actioncal/_medium.scss
src/scss/panes/_medium.scss

Fix several styling related issues that have arisen due to recent updates.
* Optimize pane transition into and out of `scrolled` state.
* Fix incorrect offsets in min-calendar, causing it to "bleed" left and right.
* Offset content of `ActionDistributionPane`, which was being obscured by mini-calendar.
* Re-tweak styling of subtitles, which was disabled due to selects no longer being valid.

Fix styling issues

---

src/js/server/widgets.js

A recent change to the OpenWeatherMap API introduces API keys as a requirement. This PR adds the ability to configure the API key using an environment variable.

OpenWeaterMap API key

---

src/actions/index.js
src/actions/query.js
src/components/panes/EditQueryPane.jsx
src/components/panes/QueryPane.jsx
src/components/sections/people/PeopleListPane.jsx
src/server/search.js
src/store/queries.js

This PR properly hooks up the person query feature to the relevent APIs. Person queries were previously implemented as a placeholder/dummy feature using LocalStorage, but was replaced with no-op actions as part of the #237 Redux refactor.

Hook up person queries to API

---

src/components/filters/FilterList.jsx
src/components/filters/FilterListItem.jsx
src/components/filters/PersonTagsFilter.jsx
src/components/filters/index.js
src/components/panes/EditQueryPane.jsx

This PR adds a `PersonTagsFilter` component to render and edit the `person_tags` query filter type. It depends on a rather ugly hack of passing in `openPane()` into all filters (bd33565) that should be removed once pane logic has been moved to redux and panes can be opened using actions, as discussed in #245.

Person tags filter

---

src/components/lists/items/elements/ParticipantItem.jsx
src/components/lists/items/elements/ParticipantList.jsx
src/components/panes/ActionPane.jsx
src/components/panes/ActionPane.scss
src/components/panes/CallAssignmentPane.jsx
src/components/panes/index.js
src/components/sections/campaign/AllActionsPane.jsx
src/components/sections/campaign/CampaignSectionPaneBase.jsx
src/server/datarouter.js

This PR adds a new `ActionPane` summary pane, to replace `EditActionPane` in most cases (except when user explicitly wants to edit the action). The `ActionPane` contains (or will at some future point contain):
* Action summary (time, location et c)
* Organizer notes for action
* List of action participants
* List of responses to be booked to action

Action summary pane

---

src/components/misc/Avatar.jsx

The avatars feature has been completely revamped in the Zetkin Platform. Avatars are no longer requested from a separate application, but instead using the `/avatar` suffix on the person API endpoint, which will redirect to the location of the static avatar file.
This PR updates the `Avatar` component to use this new scheme.

Use new URL scheme for avatars

---

.gitmodules
src/actions/person.js
src/actions/search.js
src/components/filters/CallHistoryFilter.jsx
src/components/filters/CampaignFilter.jsx
src/components/filters/FilterBase.jsx
src/components/filters/PersonTagsFilter.jsx
src/components/forms/inputs/RelSelectInput.jsx
src/components/header/Header.jsx
src/components/header/OrgPicker.jsx
src/components/header/OrgUserMenu.jsx
src/components/header/OrgUserMenu.scss
src/components/header/search/Search.jsx
src/components/lists/PersonList.jsx
src/components/lists/items/CallAssignmentListItem.jsx
src/components/misc/actioncal/ActionDay.jsx
src/components/panes/SelectPeoplePane.jsx
src/components/sections/people/ImportPane.jsx
src/components/sections/people/PeopleListPane.jsx
src/scss/_mixins.scss
src/server/app.js
src/store/callAssignments.js
src/store/index.js
webpack.config.js

This PR contains fixes for several priority bugs ahead of the January launch.
* Remove draft references from URL when reloading (#246)
* Redirect if logged out (#327)
* Hide action clone hint since cloning doesn't work (#337)
* Fix incorrect message ID in import pane (#351)
* Load call assignment basic data, stats and callers in correct order (#343)
* Re-open search socket after error/close (#266)
* Increase delays on input blur (#304, #353)
* Disable pagination in SelectPeoplePane (#345)
* Emit initial config from filters using `onFilterChange` on `componentDidMount` (#260)
* Default to "all" for `PersonTagsFilter` (#354)

Fixes to misc priority bugs

---

locale/panes/allActions/sv.yaml
locale/panes/sv.yaml
src/actions/action.js
src/client/main.js
src/components/forms/inputs/DateInput.jsx
src/components/misc/actioncal/ActionCalendar.jsx
src/components/panes/PaneBase.jsx
src/components/panes/PaneBase.scss
src/components/sections/RootPaneBase.jsx
src/components/sections/RootPaneBase.scss
src/components/sections/Section.jsx
src/components/sections/campaign/ActionDistributionPane.jsx
src/components/sections/campaign/ActionDistributionPane.scss
src/components/sections/campaign/AllActionsPane.jsx
src/components/sections/campaign/CampaignPlaybackPane.jsx
src/components/sections/campaign/CampaignSectionPaneBase.jsx
src/components/sections/dialog/AllCallAssignmentsPane.jsx
src/components/sections/dialog/CallAssignmentTemplatePane.jsx
src/components/sections/dialog/CallLogPane.jsx
src/components/sections/maps/LocationsPane.jsx
src/components/sections/people/ImportPane.jsx
src/components/sections/people/InvitePane.jsx
src/components/sections/people/PeopleListPane.jsx
src/components/sections/settings/OfficialsPane.jsx
src/server/main.js
src/store/actions.js
src/utils/PaneManager.js

This PR moves filter-type controls from the regular section toolbar to a new filter drawer, which opens and closes at the click of a button in the regular toolbar.
It also implements filtering of actions by date, and refactors the pane class hierarchy so that section root panes and "regular" floating panes inherit separate base classes (`RootPaneBase` and `PaneBase` respectively), as outlined in #319.
This PR does not however implement any nice styling of the added drawers (tracked for future reference by #373).
Fixes #366

Filter drawer

---

src/components/lists/items/ActionListItem.jsx
src/components/lists/items/CallAssignmentListItem.jsx
src/components/lists/items/ListItem.jsx
src/components/misc/actioncal/ActionCalendar.jsx
src/components/misc/actioncal/ActionDay.jsx
src/components/misc/actioncal/ActionItem.jsx
src/components/panes/LocationPane.jsx
src/components/panes/QueryPane.jsx
src/components/sections/campaign/AllActionsPane.jsx
src/components/sections/campaign/CampaignSectionPaneBase.jsx
src/components/sections/dialog/AllCallAssignmentsPane.jsx
src/components/sections/maps/LocationsPane.jsx
src/components/sections/maps/MapOverviewPane.jsx
src/components/sections/people/PeopleListPane.jsx

This PR adds a feature where alt-clicking an item in a list (or in the case of locations, on a map) does not opens the respective edit panes for the item's type. Alt-clicking a person in `PersonList` opens the `EditPersonPane` instead of the `PersonPane`.
This is particularly nice in the case of actions in the calendar. While planning a campaign, you rarely want to open the `ActionPane`, but instead edit the action using the `EditActionPane`.

Alt-clicking for quick edit

---

locale/panes/callAssignment/sv.yaml
locale/panes/editQuery/sv.yaml
src/components/filters/CampaignFilter.jsx
src/components/panes/CallAssignmentPane.jsx
src/components/panes/CallAssignmentPane.scss
src/components/panes/EditQueryPane.jsx
src/store/queries.js

This PR makes several minor improvements to the call assignment query editing interface. It uses the new `type` attribute on queries to determine what content to show in `EditQueryPane` (form unnecessary for call assignment queries). It also fixes some minor issues regarding queries in the `CallAssignmentPane`.

Enhanced assignment query UI

---

locale/filters/all/sv.yaml
locale/filters/random/sv.yaml
locale/filters/sv.yaml
locale/panes/addCallAssignment/sv.yaml
src/components/filters/AllFilter.jsx
src/components/filters/FilterList.jsx
src/components/filters/RandomFilter.jsx
src/components/filters/index.js
src/components/forms/inputs/RelSelectInput.jsx
src/components/misc/callAssignmentTemplates/AllTargetTemplate.jsx
src/components/misc/callAssignmentTemplates/RandomTargetTemplate.jsx
src/components/panes/AddCallAssignmentPane.jsx

This PR adds the two recently implemented filters `all` and `random`. It adds filter widgets for the query pane, and two new templates for call assignment targets based on these filters.
There are features in the `random` filter that are not supported in this version of the UI, namely seeding and fractional sizes (e.g. to select 50% instead of an exact number of people). They will be implemented in the future (#404).
Closes #355 
Closes #356

New query filters

---

locale/misc/sv.yaml
src/components/misc/officiallist/OfficialList.jsx
src/components/misc/officiallist/OfficialListItem.jsx
src/components/misc/officiallist/OfficialListItem.scss
src/components/sections/settings/OfficialsPane.jsx

This PR prevents the user from changing their own role in `OfficialsPane`, by substituting `DraggableAvatar` for the regular `Avatar` component and adding a label that explains that the role is locked.
Fixes #384

Prevent changing user's role

---

src/components/lists/List.jsx
src/components/lists/List.scss
src/components/sections/people/PeopleListPane.jsx

This PR adds UI for selecting multiple items in a list. A checkbox at the top lets the user select all the (visible) items in a list. Holding shift while clicking selects all the items between two items.
Closes #464

Multi-select in lists

---

src/server/api/bulk.js
src/utils/import.js

This PR fixes an issue which was causing an all-null row to be included at the end of an exported XLSX file. It also tweaks the importer to ignore such rows, should they still occur, e.g. in old files.
Fixes #484

Person IO null rows

---

locale/forms/survey/sv.yaml
locale/forms/surveyQuestion/sv.yaml
src/components/forms/SurveyForm.jsx
src/components/forms/SurveyQuestionForm.jsx

This PR adds survey options that are in the API but were previously not accessible through the Organize UI:
* Whether to allow anonymous signatures on surveys
* Widget settings (`response_config`) for questions

Missing survey options

---

locale/panes/callLog/en.yaml
locale/panes/callLog/sv.yaml
src/actions/call.js
src/components/sections/RootPaneBase.jsx
src/components/sections/dialog/CallLogPane.jsx

This PR adds a filter drawer for the call log. It also makes some changes to the surrounding frameworks, making it easier to create stateful filter drawers in the future.
This contains the most urgent filters explained in #445. The rest can be added later.

Call filters

---

locale/panes/allActions/en.yaml
locale/panes/allActions/sv.yaml
src/components/sections/campaign/AllActionsPane.jsx
src/components/sections/campaign/AllActionsPane.scss
src/components/sections/dialog/AllCallAssignmentsPane.jsx
src/components/sections/dialog/AllCallAssignmentsPane.scss
src/components/sections/maps/LocationsPane.scss
src/components/sections/people/PeopleListPane.scss
src/components/sections/survey/SurveyListPane.scss

Adding button to add Action (open addActionPane) in the toolbar of AllActionsPane.
By this, a vulnerability from a UX point of view arouse. Two essentially different types of buttons - those that alters the current pane (how and what to view) and those that moves to a different setting (like creating a new of what is listed in the mother pane). Having these in a mixed order would make them to compete for users attention and understanding of the area and the tools within.
By separating these types of buttons, the users learns that there is dedicated places for these different actions which increases the workflow speed.
In UX design, the right corners is usually recommended for confirming or to continue to next step in workflow, in this context - to create or add something. The left corners …

Tweak add buttons

---

locale/misc/en.yaml
locale/misc/sv.yaml
src/components/forms/inputs/RelSelectInput.jsx
src/components/forms/inputs/RelSelectInput.scss
src/components/misc/DraggableAvatar.jsx
src/components/misc/PersonSelectWidget.jsx
src/components/misc/PersonSelectWidget.scss
src/components/panes/ActionPane.jsx
src/components/panes/ActionPane.scss

This PR adds a new widget called `PersonSelectWidget`, suitable for selecting a single person inline, e.g. the contact for an action or the manager for a campaign. It supports both drag/drop and selecting from a list (`RelSelectInput`).
The PR also implements this new widget in a few locations.
Fixes #602
Fixes #603

Person select widget

---

locale/lists/addressList/en.yaml
locale/lists/addressList/sv.yaml
locale/panes/allRoutes/en.yaml
locale/panes/allRoutes/sv.yaml
locale/panes/routeContent/en.yaml
locale/panes/routeContent/sv.yaml
locale/panes/selectStreetAddress/en.yaml
locale/panes/selectStreetAddress/sv.yaml
src/actions/selection.js
src/components/forms/inputs/RelSelectInput.jsx
src/components/lists/AddressList.jsx
src/components/lists/AddressList.scss
src/components/lists/items/AddressListItem.jsx
src/components/misc/PersonSelectWidget.jsx
src/components/panes/RouteContentPane.jsx
src/components/panes/RouteContentPane.scss
src/components/panes/RoutePane.jsx
src/components/panes/SelectStreetAddressPane.jsx
src/components/panes/SelectStreetAddressPane.scss
src/components/panes/index.js
src/components/sections/canvass/AllRoutesPane.jsx
src/store/addresses.js
src/utils/location.js

This PR adds the `RouteContentPane` and the `SelectStreetAddressPane`, which lets the user edit route content by adding addresses. Since this has not been hooked up to the API, this is just a UI with some in-memory storage for now.

Canvass route address panes

---

locale/header/en.yaml
locale/header/sv.yaml
src/actions/index.js
src/actions/user.js
src/components/header/OrgPicker.jsx
src/server/app.js
src/store/org.js
src/store/user.js

This PR refactors the way organization switching works. Starting with this PR, switching organizations will always result in a full page refresh, and the active organization will be remembered across refreshes (and sessions) using a cookie.
Fixes #672

Org switching

---

src/components/KeyboardShortcuts.jsx

This replaces use of non-standard `keyCode` with `charCode` and `key` as needed.
Fixes #592

Fix keyboard shortcuts in Firefox

---

locale/alerts/en.yaml
locale/alerts/sv.yaml
locale/dashboard/en.yaml
locale/dashboard/sv.yaml
src/actions/alert.js
src/actions/index.js
src/components/App.jsx
src/components/dashboard/Dashboard.jsx
src/components/dashboard/Dashboard.scss
src/components/misc/AlertMessages.jsx
src/components/misc/AlertMessages.scss
src/components/misc/campaignplayer/CampaignPlayer.jsx
src/components/sections/campaign/CampaignPlaybackPane.jsx
src/components/sections/campaign/CampaignPlaybackPane.scss
src/components/sections/index.js
src/store/alerts.js
src/store/index.js

This PR contains a number of smaller improvements to the Organize interface.
The manage section that was implemented in the last release but hidden, is now made visible.
As outlined in #730, a message is added on the dashboard that includes the name of the current organization.
Fixes three issues related to the `CampaignPlayer`. One undocumented issue related to how the order in which actions were stored affected the playback span, one missing import in `CampaignPlaybackPane` and a third one as described in #658.
Adds a framework for alert messages to display in the bottom left corner, and logic to display a message whenever an API request results in a 403 (unauthorized) error.
Issues #745, #746, #747 and #748 describe future improvements to and use cases for this framework.

Misc improvements

---

locale/forms/campaign/en.yaml
locale/forms/campaign/sv.yaml
src/actions/campaign.js
src/components/forms/CampaignForm.jsx
src/components/panes/AddCampaignPane.jsx

This PR exposes the `published` property of campaigns in `CampaignForm` so that it's possible to change it when creating/editing a campaign.
Fixes #402

Campaign drafts

---

locale/forms/callAssignment/sv.yaml

sv.yaml: callAssignment form: Fix typo in label, ringar -> ringare

---

bin/run_dev
bin/run_dev.cmd

This avoids this error in startup:
> [node] (node:62) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Encryption secret must be a 24 character string!

run_dev script: include a 24-digit character TOKEN_SECRET

---

locale/header/en.yaml
locale/header/sv.yaml
src/actions/search/index.js
src/components/header/search/Search.jsx
src/components/header/search/Search.scss

This PR adds back a feature that was there before the search refactor, restricting searches to a minimum of three characters. It now also shows a message until the string is long enough.

Minimum search string

---

src/components/lists/items/ActionListItem.jsx

Fix an undocumented bug that caused exceptions to be thrown when dragging persons to actions, because the participants would not have loaded.

Person drag and drop bug

---

locale/filters/campaign/en.yaml
locale/filters/campaign/sv.yaml
locale/filters/en.yaml
locale/filters/subQuery/en.yaml
locale/filters/subQuery/sv.yaml
locale/filters/sv.yaml
src/components/filters/CampaignFilter.jsx
src/components/filters/FilterList.jsx
src/components/filters/SubQueryFilter.jsx
src/components/filters/index.js
src/components/forms/inputs/SelectInput.jsx

This PR adds a bunch of new filtering capabilities for Smart Searches:
* Include signed-up but not booked participants in campaign participation filter
* Filter by activity/location in the campaign participation filter (#845)
* New sub-query filter for both standalone queries and call assignments (#849, #850)
It also introduces support for `<optgroup>`s in `SelectInput`.

More filters

---

README.md
bin/run_dev

This PR updates the README to include instructions for logging in: the SMS challenge is set to the fixed number `999999` in development.
Also: update the APP_ID

README: note the SMS challenge number, update the APP_ID

---

locale/panes/query/en.yaml
locale/panes/query/sv.yaml
src/components/panes/QueryPane.jsx
src/components/panes/QueryPane.scss

This PR adds an `InfoList` section to Smart Searches:
- description
- search result count
Closes #564
Closes #855

QueryPane: InfoList with description and search result count

---

src/server/api/duplicates.js

This PR optimizes the duplicate search using the following strategies:
* Calculate normalized values for person attributes once, and reuse
* Don't pop/splice lists, use indices and flags instead
* Don't create a duplicate object unless duplicates are found
These benchmarks were measured using real-life data in a mid-size and large organization respectively. The times in seconds are measured using the Chrome dev tools when making a request to the duplicate search endpoint for each of the organizations before and after the change.
| Case | Trial 1 | Trial 2 | Trial 3 | Trial 4 | Trial 5| Avg boost
|:-----|-------:|-------:|-------:|-------:|-------:|--------:|
| Mid-size org, before | 9.23 | 8.15 | 4.65 | 4.75 | 4.66 |
| Mid-size org, after | 1.77 | 1.63 | 1.67 | 1.59 | 1.62 | 4x
| Large …

Optimized duplicate search

---

src/components/lists/items/elements/ParticipantItem.scss
src/components/misc/Avatar.jsx
src/components/misc/Avatar.scss
src/components/misc/DraggableAvatar.scss

This PR adds a loading state for `Avatar` images. While the `img` loads, the avatar is displayed as a mostly translucent, pulsating square. When the image finishes loading, it fades in.

Implement loading state for Avatar images

---

src/actions/search/index.js
src/components/header/search/matches/MatchBase.scss
src/components/lists/items/elements/ParticipantItem.scss
src/components/lists/items/elements/ParticipantList.scss

This PR contains two bug fixes and one separate improvement:
* Tweaks avatar sizing in `ActionListItem` participant list, fixes #890
* Tweaks avatar sizing in search matches, fixes #887 
* Re-orders search ops so that searching for people is prioritized over (almost) everything else

Avatar sizing (and other improvements)

---

locale/panes/allActions/da.yaml
locale/panes/allActions/en.yaml
locale/panes/allActions/sv.yaml
src/components/lists/items/ActionListItem.jsx
src/components/sections/campaign/CampaignSectionPaneBase.jsx
src/store/actions.js

This PR fixes #915.
- Actions Calendar filters: introduce `notgreen`, `notred` statuses
- Translate statuses (da, en, sv)
- Change: `red` now also includes "an action which requires 1 and needs 1 participant" (whereas before red meant: "an action which needs 2 participants", which would exclude all 1-person jobs) See #918 374
When rendering the participation level indicator, we mark _any_ activity with 0 participants as "red".

Add availability statuses notred, notgreen

---

src/components/panes/BulkOpPane.jsx
src/store/bulk.js
src/store/index.js
src/store/people.js

This PR introduces a new Store, `bulk`, adds it to collection of Stores, and then uses it in the BulkOpPane's "state".
See #913

Store: Introduce bulk.js

---

locale/panes/query/en.yaml
locale/panes/query/sv.yaml
locale/panes/queryDiff/en.yaml
locale/panes/queryDiff/sv.yaml
src/components/panes/QueryDiffPane.jsx
src/components/panes/QueryDiffPane.scss
src/components/panes/QueryPane.jsx
src/components/panes/QueryPane.scss
src/components/panes/index.js

This PR adds a new `QueryDiffPane` for comparing the results of two Smart Search queries. This is WP.
Fixes #901

Query diff pane

---

src/components/panes/CallPane.jsx
src/components/panes/CallPane.scss

This PR adds the title of a Call assignment to CallPane (the pane that inspects a specific report form the call log). We are following the same layout as in Survey submissions.
The title is retrieved from the assignment by fetching the right assignment based on a specified assignment ID in the call object. Since we can't load the assignment before we have the call and this id, we will have to await this first.
When rendering, we add the div with class `CallPane-info` and add the title to this.
Fix #865

Add assignment to CallPane

---

src/components/forms/inputs/DateInput.scss
src/components/forms/inputs/InputBase.jsx
src/components/forms/inputs/InputBase.scss
src/components/forms/inputs/RelSelectInput.scss
src/components/forms/inputs/SelectInput.jsx
src/components/forms/inputs/SelectInput.scss
src/scss/_mixins.scss

This PR moves styling relating to input fields from a global mixin called `form-base` to be more component specific. This styling is now in the component `InputBase`. All Input components inherits this.
We are however still to use the global mixin `input-base`, since this is shared with components outside of this scope.
Also removed unnecessary use of `input-base` in some of the input components.
Fix #568

Move styling to Input

---

src/components/misc/actioncal/ActionCalendar.scss
src/components/misc/actioncal/ActionDay.scss
src/components/panes/PaneBase.scss

I've made some changes in the Action Calendar styling. It had turned the other way round due to new media queries (small screens had the desktop styling and vice versa). I hope and think it looks as it should now, but please take a closer look.

Action calendar styling 

---

locale/panes/action/en.yaml
src/components/panes/ActionPane.jsx
src/components/panes/ActionPane.scss

If not all participants notifications has been sent, checks to see if time of action has passed. If so, displays related message with reminder status "missing".
Fixes #974

Hide send reminder ActionBox button for past actions

---

src/actions/bulk.js
src/components/sections/people/PeopleListPane.jsx
src/server/api/bulk.js
src/store/people.js

This PR contains several fixes to issues related to bulk-deleting people.
* Prevent deleting oneself through bulk delete. Fixes #975 
* Fix undocumented bug caused by exception thrown after a bulk operation finishes
* Correctly remove people from store after bulk-deleting them

Bulk delete bug fixes

---

src/components/misc/ViewSwitch.scss
src/components/sections/RootPaneBase.scss
src/components/sections/people/ManagePeoplePane.jsx
src/components/sections/people/ManagePeoplePane.scss

This PR fixes a few minor layout issues that were found since the mobile layout implementation:
* `ViewSwitch` which is fixed at the bottom should not be transparent. Fixes #971 
* Adapt duplicate search results for mobile screen widths. Fixes #972 
* Fix overlap in filter drawer. Fixes #973

Mobile layout tweaks

---

locale/misc/en.yaml
src/actions/survey.js
src/components/misc/surveyOutline/SurveyQuestionOutline.jsx
src/components/misc/surveyOutline/SurveyQuestionOutline.scss
src/components/panes/EditSurveyQuestionPane.jsx

This PR adds an interface to create multiple response options for a survey question at once. A new button to "add multiple" is added next to the existing "add response option" one. Clicking it presents a `textarea` where the user can type several options, one per line, before clicking a button to have them all created in one go.
Fixes #922

Bulk create survey options

---

locale/panes/linkSubmission/en.yaml
src/components/panes/AddPersonPane.jsx
src/components/panes/LinkSubmissionPane.jsx
src/components/panes/LinkSubmissionPane.scss

This PR adds suggestions to the `LinkSubmissionPane` to make linking survey submissions more efficient. With these changes:
* Zetkin suggests person objects that match the e-mail address of the respondent, closes #968
* The user can create a new person from the respondent information, closes #967
* The user can create a new (empty) person for anonymous submissions

Survey linking hints

---

src/components/panes/ActionPane.jsx

This PR adds a conditional statement for `action.campaign` in ActionPane InfoList. Like activity and location, if action campaign is undefined the corresponding list item value is set to an empty string.
Fixes #987

Fix cannot read property title of action.campaign bug

---

src/components/filters/SurveySubmissionFilter.jsx

Fixes #934 
Issue was related to Chrome datepicker at times sending an empty string as value. By checking if value exists in `onChangeSimpleField`, setState callback wont trigger an update of component props with `after` set to empty string, thus not resetting `timeframe` to null when mapping state from config.
This PR also sets `state.after` to correctly formatted date string passed in as `config.after` in `stateFromConfig`. Previously, `state.after` was set to Date object resulting in the datepicker not displaying the date value.

Fix SurveySubmissionFilter datepicker bug

---

locale/filters/en.yaml
locale/filters/mostActive/en.yaml
src/components/filters/CampaignFilter.jsx
src/components/filters/FilterList.jsx
src/components/filters/FilterTimeFrameSelect.jsx
src/components/filters/MostActiveFilter.jsx
src/components/filters/index.js

This PR introduces the new _Most active campaigners_ filter which was recently introduced to the Zetkin Platform, which lets you select in your Smart Search queries the people who have been most active in campaigns during a specific timeframe.
Closes #999

Most active filter

---

locale/filters/surveySubmission/en.yaml
src/components/filters/FilterTimeFrameSelect.jsx
src/components/filters/SurveySubmissionFilter.jsx

This PR fixes the survey submission filter bug documented as #998, by using the recently introduced `FilterTimeFrameSelect` component instead of a bespoke solution. It also enhances `FilterTimeFrameSelect` to make the `future` option optional, and disables it in the context of survey submissions (which cannot have been submitted in the future).
Fixes #998

Fix survey submission filter bug

---

locale/panes/import/en.yaml
locale/panes/import/sv.yaml
package.json
src/actions/importer.js
src/utils/import.js

This PR adds support for parsing and importing CSV files.
You can try with any CSV file, including most variations for delimiters, quotes et c. If the format is not recognized by the parser, a proper error is shown.
The CSV parser isn't quite as fancy as the Excel parser, but some of that is because the format itself is not as fancy. For example, the CSV parser will not look for a header (because there is no formatting) and hence will also not guess the contents of each column.
It will also not remove empty columns, which could theoretically be done but is not a prioritized feature and should probably be refactored into some general-purpose solution eventually.
Closes #1054

CSV import

---

bin/run_dev.cmd
gulpfile.js
webpack.config.js

This PR contains changes to the development environment to accommodate Windows developers.
* The `run_dev.cmd` script is amended to allow spaces in volume directory names
* Environment variables are given correct values for development
* Polling in `gulp-watch` and `webpack` replace the old `docker-volume-watcher` solution

Windows dev environment fixes

---

src/server/api/bulk.js

Fixes #937 
Fixes #1007
This seems to have been introduced by #984, which prevents users from deleting themselves by checking their memberships and filtering their profile out of the people that are about to be deleted.
The issue is that organization ID is sometimes(?) sent as a string and sometimes as an integer, but was compared using strict equality (`===`). This meant that sometimes no matching membership would be found, causing an exception.
Just switching to `==` means that a membership will always be found. If for some reason it's not, this should fail anyway.

Fix error when bulk deleting people

---

src/components/filters/PersonDataFilter.jsx

This PR fixes an undocumented issue with the name of the zip code field in `PersonDataFilter`. It was named `zip` but is expected by the Zetkin platform API to be named `zip_code`.
Steps to reproduce (before applying this fix):
1. Create a new Smart Search Query, name it whatever
2. Add a new Person Data filter
3. Set the field to search for to Zip
4. Type in any Zip
5. Save the query
Expected result: API should accept input
Actual result: API rejects input

Fix incorrect field name for zip code in PersonDataFilter

---

src/components/panes/PersonPane.jsx

Fixes undocumented bug which prevented custom fields from being displayed.
This bug was introduced in #1078, which only retrieves the custom field types in the `PeopleListPane`, but that pane doesn't always precede the `PersonPane`. The bug could be reproduced as such:
1. Refresh Organize on the home page with dummy org 1 (to reset state)
2. Navigate to Campaign section
3. Search for a person
4. Pick any of the search results – `PersonPane` opens over campaign section
Expected results: `PersonPane` should contain info about custom fields
Actual results: `PersonPane` does not contain the custom fields section because it does not find any field types

Retrieve field types in PersonPane

---

src/components/panes/ConfirmImportPane.jsx

There is a bug where two columns of the same person_field data-type, but with different IDs, triggered a duplicate column error in the client-side validation. This pull request fixes that. The solution, with a regex-match in a switch-statemnt, is not very pretty, but rewriting the whole thing with a dozen if-statements is not very pretty either.

Fix duplicate person_field bug

---

src/components/misc/Avatar.jsx
src/components/misc/Avatar.scss

This PR sets the "new" `loading="lazy"` attribute on the `<img>` element in `Avatar`, as discussed in #1129. Because it can't be done through the declarative React JSX (because our version of `react-dom` is too old) I've done it using the regular DOM API post mount. It seems to work just fine without performance issues.
The PR also sets avatars to always be square, regardless of width, using the `padding-top` CSS trick. This was always a bit of an issue causing avatars to flicker as they loaded, but it became even more obvious when lazy-loaded.
Fixes #1129

Lazy-loading Avatar

---

src/components/misc/Avatar.scss
src/components/misc/personViews/PersonViewTableRow.scss

This PR reverts Avatar dimension styling introduced by 3a4111a5d6ba506f6cb68c1b00c5c7e96f45213f in #1131. Instead of trying to make it square using the `padding-top: 100%` trick, which was causing issues in multiple places, `Avatar` now relies on it's context to set both width and height.

Revert to old Avatar dimension logic

---

locale/misc/pageSelect/en.yaml
locale/misc/personViewTable/en.yaml
package.json
src/components/misc/PageSelect.jsx
src/components/misc/PageSelect.scss
src/components/misc/personViews/PersonViewTable.jsx
src/components/misc/personViews/PersonViewTable.scss

This PR introduces a new "toolbar" to Views, adding search, pagination and export capabilities.
* As-you-type search for plaintext cells in the view (does not support survey responses at this point)
* Pagination with a 500 row page limit, which is necessary for performance
* Export entire view (all pages) as CSV file
Closes #1108 
Closes #1116
Closes #1117

View tools (export, search, pagination)

---

src/components/panes/AddViewColumnPane.jsx

Support custom fields in view columns of type `person_field`.
To test:
1. Navigate to Views
2. Create a view
3. Click "Add Column"
4. From the "Person field" settings, select a custom field
If there are no custom fields, make sure one exists. Either add through the API or reset development data if possible.

Custom field view columns

---

src/store/personViews.js

This PR fixes an undocumented error caused when trying to add the same row twice to a view (or indeed any other operation which causes an error). Previously the `addIsPending` would not be updated, so the spinner in the person select box would not be removed. This PR fixes that.

Handle error when adding row to view

---

locale/panes/confirmExport/en.yaml
locale/panes/confirmExport/sv.yaml
src/actions/personView.js
src/components/misc/personViews/PersonViewTable.jsx
src/components/panes/ConfirmExportPane.jsx
src/components/panes/ConfirmExportPane.scss
src/components/panes/index.js
src/components/sections/people/PersonViewsPane.jsx

This PR adds a new pane which is opened when the user clicks to download a view as CSV. The pane contains a message and a button to execute the download.
In the future, we can add options here to configure whether the download should contain all objects or just the visible ones (after filtering).
Closes #1147

Confirm CSV export

---

src/components/misc/personViews/PersonViewAddRow.jsx
src/components/misc/personViews/PersonViewAddRow.scss
src/components/misc/personViews/PersonViewTable.jsx
src/components/misc/personViews/PersonViewTable.scss
src/components/misc/personViews/PersonViewTableHead.jsx
src/components/misc/personViews/PersonViewTableHead.scss
src/components/misc/personViews/PersonViewTableRow.jsx
src/components/misc/personViews/PersonViewTableRow.scss
src/components/misc/personViews/cells/SurveyResponseCell.scss
src/components/sections/people/PersonViewsPane.scss

This PR makes a number of improvements to the experience when working with large views that require scrolling.
* Fixate view table to browser viewport, so that horizontal and vertical scrollbars are visible. Fixes #1174 
* Keep table header sticky at top. Fixes half of #1118 (sticky avatars proved very complex and must be postponed)
* Add cell outlines Fixes #1155 
See screenshots below for examples of what this looks like in default state, when scrolled a little bit in both directions, and the new location of the "Add" widget at the bottom.

View scrolling improvements

---

src/components/misc/personViews/PersonViewTable.jsx

This PR handles cells in `survey_response` columns properly when searching in a view. These cells include an array of objects, each object representing a response to the given survey question. The logic merges the array into a single string and searches it the same way that regular search in text-based cells work.
Fixes #1142

Handle survey_response cells when searching in view

---

src/components/panes/MergePeoplePane.jsx

This PR adds capabilities to select which custom field values to keep after a person merge. To test it, create some duplicates with conflicting custom field values, and try merging. While merging, try selecting different values. Also try merging when there are no custom fields on a person, or when only one of the duplicates has values assigned.
Closes #1162

Custom field overrides during merge

---

locale/misc/fields/en.yaml
locale/panes/joinSubmission/en.yaml
src/components/panes/JoinSubmissionPane.jsx
src/components/panes/JoinSubmissionPane.scss

This PR makes the following changes to JoinSubmissionPane:
* Show all form fields while submission is pending. Fixes #1169
* Move meta-data section to top of pane and add icons
* Tweak styling

More information in JoinSubmissionPane

---

src/components/misc/personViews/PersonViewTable.scss
src/components/misc/personViews/PersonViewTableHead.scss
src/components/misc/personViews/PersonViewTableRow.scss

This PR fixes some misalignment issues between table header and rows, especially in Firefox, but also in some cases on Chrome. Related to view scrolling, so make sure to test with a wide and tall view.

Fix minor styling issues for views in some browsers

---

src/actions/personView.js

Creating a person view column from a survey question results in the column title having the same title as the survey question. But the max length of a survey question is over 200 characters whereas the max length of a column title is 80 characters.
This fix truncates column titles in the createPersonViewColumn action before it is sent to the server.

BUGFIX: Truncate view column title to a max of 80 characters

---

package.json

This PR is a repair PR for the installation of this app. Paired with @oelrich to build this!
We picked a new version specifier for `gulp-sass` to fix the issue.
Any newer version currently fails to build. The newer versions that 3.0.0 all also fail. We attempted them all and found ^3.0.0 to pick a working version.
The underlying issue was that the ^2.2.0 version specifier tried to download a node-sass which had been removed from that project's GitHub Releases download section. This failed installs in the Docker build.
Error message before this change:
```
> node-sass@3.13.1 install /var/app/node_modules/node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-64_binding.node
Cannot download …
```

Pin gulp-sass to the newest-working version 3.0.0

---

src/components/sections/people/PersonViewsPane.jsx

The queryId passed to the confirmexport component needs to be
blank to be able to export the "Saved" tab.
We made it so that any selected queryId in the Smart Search is retained when clicking that button. (Like, when you leave the Saved for the Smart Search button.)
Fixes #1217.
Pair-programmed with @oelrich

Fix: PersonViewsPane: Download users in active view

---

src/components/sections/people/PersonViewsPane.jsx
src/components/sections/people/PersonViewsPane.scss

This PR tweaks the "back" and "collapse" links for person views:
* Makes the entire link clickable, including the chevron icon
* Moves the chevron of the "collapse" link to the right-hand side
* Animates chevron by rotating it (see animation below)

Tweak collapse/back links in person view

---

src/components/filters/PersonFieldFilter.jsx

Fix bug where PersonFieldFilter will not render properly if fieldTypes is not available when class constructor is run.
Resolves #1250

Fix custom field query rendering bug

---

src/components/panes/AddViewColumnPane.jsx

Fix undocumented bug where adding a view column without selecting anything would add a person_field filter with the configuration of a person_note.
To reproduce:
1. Create a view
2. Add a few people to the view
3. Click Add column
4. Click the Add column button in the AddViewColumnPane
Expected results: Adds the selected view column type
Actual results: Adds a column named Person notes, clears people from the view due to the backend not knowing what to do with the odd column configuration.

Fix AddViewColumn bug

---

src/actions/personView.js

Resolves #1260 
Does not include slug exactly because it's not available without making changes to the way the platform returns organizations, instead merely returns a lowercased organization title stripped of any non-a-z-characters.

Include slug in export file name

---

src/components/forms/inputs/RelSelectInput.jsx

Automatically scroll to the currently selected element in the RelSelectInput when focused.
Resolves #1240

Scroll to selected element in RelSelectInput after focus

---

src/server/app.js
src/server/datarouter.js

This PR fixes #798 by changing the order in which various middleware handle a request on the server-side. Before it went like this:
1. Set up store
2. Preload data
3. Set correct org from cookie
With this change, the order is now:
1. Set up store
2. Set correct org from cookie
3. Preload data

Preload data from correct org

---

src/server/datarouter.js

Resolves #1286
This is a workaround for the server-client inconsistency for actions. It proved difficult to fix, so this PR simply removes preloading of actions on server render. The consequences of this may be a slight delay for displaying actions on reload or direct url entry of e.g. /campaign/actions on slower connections.

Workaround for server-client inconsistency with actions

---

locale/forms/query/en.yaml
locale/forms/query/sv.yaml
locale/panes/query/en.yaml
locale/panes/query/sv.yaml
src/components/forms/QueryForm.jsx
src/components/forms/inputs/RelSelectInput.jsx
src/components/panes/QueryPane.jsx
src/components/panes/QueryPane.scss
src/components/sections/people/PeopleListPane.jsx
src/components/sections/people/PersonViewsPane.jsx

Add selectbox for choosing access level of queries.
Show the owner of a parent org query and show the status of organization sharing for the organizations own queries. Remove link to edit pane for parent query.
Remove edit link from query select box for parent queries.

Suborg acces in Organize gui

---

src/components/filters/SurveyOptionFilter.jsx
src/components/filters/SurveyResponseFilter.jsx
src/components/filters/SurveySubmissionFilter.jsx
src/components/sections/people/PeopleListPane.jsx
src/utils/filterByOrg.js

This fixes a bug that occasionally appears, especially with complex queries, where the survey related filters would crash due to the lack (presumably because it has not been properly loaded yet) of survey.organization.

Fix bug where survey filters sometimes crash.

---

src/actions/survey.js

Fix bug that appears when many conditions are in a query which causes organize to crash and make it impossible to edit the query.
To reproduce:
1. Make a new query
2. Add a bunch of survey response queries (like 10 or more)
3. Save
4. Go to / and reload organize.
5. Go to people and edit the query
Expected results:
You should be able to edit the query.
Actual results:
Many of the survey fields are blank and Organize crashed due to an action trying to access survey.organize which does not exist because the full survey is still pending.
(An example of this is on the live dev server, the query is called test)

Fix many surveys query bug

---

src/components/sections/dialog/AllCallAssignmentsPane.jsx
src/store/queries.js

Also fix a bug in the AllCallAssignmentsPane related to recursive fetching, don't filter on the organization for now and assume that all call assignments are fetched as normal.

Fix bug where old all filters were missing a config object. 

---

src/components/panes/AddCallAssignmentPane.jsx

Set `expose_target_details=true` by default when creating a new call assignment.
Fixes #1316

Expose target details by default

---

src/components/misc/personViews/PersonViewTable.jsx

Implement view sorting for the following column types:
`survey_option`
`survey_options`
`person_notes`
`local_person`
`survey_response`
`survey_submitted`

Fix view sorting for several column types

---

src/components/misc/personViews/PersonViewTable.jsx

Fixes sorting bug caused by new tag view column which includes values for value tags.
To reproduce bug:
1. Select a view
2. Add a tag column
3. Assign a tag to one of the people in the view
4. Click the sort button in the header of the tag column
Expected:
Column should sort on the presence of the specified tag.
Actual:
Nothing happens.

Fix sorting bug for tags caused by changes in API

---

env/app/Dockerfile
env/app/run.sh

This PR moves the building of frontend code to runtime, instead of the docker build. This is so that a single image built from the code in this repo can be used in multiple environments.

Move JS build to runtime from docker build
